### ISSUE TITLE
[CI] Share provisioning scripts between Vagrant and Travis

### ISSUE THREAD

**Issue by electricjones** [spider/spider#109]
The branch `share-vagrant-and-travis` holds my attempt to share the provisioning scripts between the two builders. I am, however, running across some headaches trying to get them both to work from different directories and it takes so long to test (because I can only test by running and letting travis run) that it is driving me crazy.

I thought I would share my work and let it sit for a bit. Maybe a fresh perspective will show us what I am doing wrong. Please feel free to tinker with this in any way.

**Comment by smolinari** [comment]
Hey Chris. Not sure how I can help, as I have little knowledge about Travis and only minimum about Vagrant, but if you have any suggestions on how I can help, let me know.

Scott

**Comment by dmill-bz** [comment]
shot in the dark but can you simple hold the path in a variable that you change depending on travis or vagrant? there are easy `if` statements to check if you're inside travis.

**Comment by electricjones** [comment]
This is closed by PR #119. Moving to docker soon
