### ISSUE TITLE
[Media] Added a logo for the repo, up for discussion

### ISSUE THREAD

**Issue by electricjones** [spider/spider#110]
I am putting together my portfolio and needed a logo for this repository (it was bothering me). I did a quick search and found this was creative commons.

https://github.com/spider/media/blob/master/organization-logo.jpg

I made it the organization logo, but am not dead set on it. Open to suggestions.

I didn't want to do a spider itself (even an abstract one) because so many people have spider fears and I just didn't want to associate the project with that bad taste.

**Comment by smolinari** [comment]
Hihihi....screwing around. Hard to be afraid of that spider, no? LOL!

![spider-logo-draft1](https://cloud.githubusercontent.com/assets/3314957/12046709/67537b8e-aebe-11e5-953a-5bb04ccddb5a.png)

I call it the Dollarback Spider. 

Scott

**Comment by electricjones** [comment]
Fun! I'm gonna leave this thread open for us to experiment with different ideas :) There's no rush, but I like the direction.
