### ISSUE TITLE
[Master] Master branch is failing -- gremlin php version problem?

### ISSUE THREAD

**Issue by electricjones** [spider/spider#113]
I'm not sure what changed, but the `master` branch is failing consistently now with the gremlin tests. I tried playing around with the versions of gremlin-php, but had no luck.

@PommeVerte would you take a look at it when you get a chance?

**Comment by dmill-bz** [comment]
Hey I just got back from holiday. I'll try pulling this and checking this week.

**Comment by dmill-bz** [comment]
posting gitter discussion : 

> yeah I saw that and I think I know why without looking at the logs.
> I suspect that the wget url from the gremlin-server travis script is not finding the url.
> Apache changed where files are stored so we need to link to the "archives" url.
> See https://github.com/jbmusso/gremlin-javascript/blob/master/build/gremlin-server/install.sh#L8

**Comment by electricjones** [comment]
Closed by commit 587d1491f9c415454f3dd54128ab001b0caf82bd
