### ISSUE TITLE
[Neo4j] The Everyman library is not compatible with PHP 7

### ISSUE THREAD

**Issue by electricjones** [spider/spider#114]
The dependency we use for the neo4j driver uses `Null` as a classname which causes tests to fail on PHP7. I know that those are allowed to fail, but not that 7 is out, I think we should strive for passing.

There is an active PR to resolve this on the dependencies repo, but it doesn't seem to be getting traction. We could pull from that PR's fork or even fork our own with those changes (its only about 4 lines) and make sure we keep up to date with the master repo until the change has been made.

Let me know what you think.

**Comment by dmill-bz** [comment]
Ideally this should be fixed on the main repo. Less work for us.
Including the link to the PR for easy tracking.
https://github.com/jadell/neo4jphp/pull/174

**Comment by electricjones** [comment]
This has been resolved in the upstream repo.
