### ISSUE TITLE
ODB is looking for PHP driver dev.

### ISSUE THREAD

**Issue by smolinari** [spider/spider#122]
Hey Chris and Dylan @chrismichaels84  @PommeVerte 

ODB is looking for a PHP dev to be in charge of the PHP driver. I thought maybe either of you might be interested. 

https://groups.google.com/forum/#!topic/orient-database/gYGKXp7tMlg

Scott

**Comment by smolinari** [comment]
I'll close the issue as soon as I know both of you have seen this.

Scott

**Comment by dmill-bz** [comment]
Cheers. I'll have a look.

**Comment by PommeVerte** [comment]
Hmm no client facing email. Not sure how to private email him

**Comment by electricjones** [comment]
Yeah, I'll take a look, too. Thanks!

**Comment by smolinari** [comment]
Great. I've also asked for Luca's email address in that thread, as that is where you need to send a resume. 

Scott
