### ISSUE TITLE
[Dev] Travis CI errors consistently with new Docker setup -- timeout?

### ISSUE THREAD

**Issue by electricjones** [spider/spider#129]
The new travis setup is fairly complex (see develop branch), and nearly every time a build is run, one of the tests fail because Neo4j never starts up. If you wait a few minutes and run the test individually it works fine.

This may involve reaching out to Travis Support.

**Comment by electricjones** [comment]
It appears to most often be the hhvm build. Restarting it (sometimes twice) will get it to pass. There should be nothing different about that build.

**Comment by smolinari** [comment]
I don't know if it has anything to do with the problem, but in my fumblings with Docker, I always noticed the Neo4J box shut down after a fairly short period of time (maybe 30 seconds or so). Maybe it is doing the same within Travis?

Scott

**Comment by electricjones** [comment]
That would actually make a lot of sense. That is really helpful.

**Comment by electricjones** [comment]
Note to developer, take a look at these issues:
- https://github.com/neo4j/docker-neo4j/issues/32
- https://github.com/neo4j/docker-neo4j/issues/20

**Comment by spacecowboy** [comment]
Also note that you might have to configure the memory options for Neo4j when running on Travis-CI. See: http://stackoverflow.com/questions/37386458/neo4j-getting-killed-in-travis-ci-container
