### ISSUE TITLE
Possible refactoring ideas

### ISSUE THREAD

**Issue by dmill-bz** [spider/spider#13]
Thought this might be a good place to put some refactoring ideas we have as things develop:
- [x] **`Object` class** : 
  Currently only Drivers take advantage of dynamic property setting via construct. Maybe we should apply this to all classes? I can definitely see Records using this, possibly even commands. Perhaps we should introduce an `Object` class that will father all other classes and provide this functionality. This would be a good place to place some getter and setter functionality as well. (see #12 )

I have an idea for this at the end of #12

**Comment by dmill-bz** [comment]
can we safely close this?

**Comment by electricjones** [comment]
Yeah, we can always open a new one for small refactors
