### ISSUE TITLE
[Builders] Add a `return` property to Bags for multiple effect situations

### ISSUE THREAD

**Issue by electricjones** [spider/spider#130]
As it stands, we have `retrieve` to set projections, that is which properties are affected (to be returned) on each vertex/edge. In each database service, however, there is also the ability to choose what is being returned in some situation, such as create or update. Do you want the entire record back? All records? Before? After? Etc?

I doubt there is much standardization here, but I feel it would be important to at least allow a lowest common denominator. 

As it stands, for both Orient and Neo4j, all affected records are returned, according to projections.

Open for discussion. I've slated this for the release after the next (0.5).

**Comment by smolinari** [comment]
Personally, I'd like to see the three options in ODB available with the `RETURN` clause. 

> RETURN Specifies an expression to return instead of the record and what to do with the result-set returned by the expression. The available return operators are:
> - COUNT Returns the number of updated records. This is the default return operator.
> - BEFORE Returns the records before the update.
> - AFTER Return the records after the update.

Scott

**Comment by dmill-bz** [comment]
I think that's not going to be an option on all servers (gremlin-server/titan won't support this behavior for example). The most important IMO is the AFTER (as you will want element IDs). There are some edge cases with temp ids but that's something that needs handling on the app layer.

I think it's best to only support the option that is covered by all dbs at the moment (after). Then go from there.

**Comment by smolinari** [comment]
Hm...ok. Will it be possible to extend Spider to cover the other options?

Scott

**Comment by dmill-bz** [comment]
No reason why you shouldn't be able to. It will kind of defeat the purpose of using spider in the first place though, since you won't be able to plug&play DBs after that change.

**Comment by smolinari** [comment]
Yeah, that will be a limitation.

On the "db swapability" bit, what are the use cases for that? I can imagine for testing backends at first, that ability would be great, but once the decision is made on which db to use, do you see users swapping out DBs often?

Scott

**Comment by dmill-bz** [comment]
Yeah. In corporate settings clients tend to already have clustered infrastructure. If they know how to use and handle neo4J, already have clusters set up etc.. It makes sense to plug neo4J in as your database. Some other client may want to use orient or titan with that same application. 

Even for yourself, you might like to use a light weight in memory graph for your dev machine but have a more robust and ressource intensive DB in production.

Some other cases are when your application outgrows your DB, maybe you started with neo but realize that titan has become a better fit as your app scaled up and required some partitioning features (or vertex centric indices. etc.) Or you use Titan and want to switch to the new Datastax DSE Graph server for better support.
