### ISSUE TITLE
I May Be Closing Up Shop

### ISSUE THREAD

**Issue by electricjones** [spider/spider#131]
Well, I hate to say this, but my time with spider may be at an end. I have been working on it over the last month because my team at work seemed we were going to use it. However, we've made a final decision, and we aren't going to be using spider (or a graph db) at all for what we need.

Add onto that, we got word that teams are mixing up, and it looks like I'll be spending most of my time on a python team, so I won't be using php much. I need to sharpen my python skills, so I doubt I will be playing with php much for the next year or so.

All that added up with hard schedules from other contributors, not a lot of interest in graph dbs from the php community, and the amount of work to be done, and I believe that is going to be it for me.

I believe in this project, and I care about it, but I cannot be the lead developer anymore. I am happy to transfer ownership if someone else wants it, and I can be around for discussion and the occasional patch. My days as a core developer are, sadly, over.

I appreciate all the help and hard work others have put into this.

Thank you,
Michael

**Comment by smolinari** [comment]
Needless to say, I am very sad to hear this news.

I wish I had the experience and capability to take over. Desire is there. It's just not enough to make Spider professional. At any rate, 

I still wish you the best in whatever endeavors you do go after and thanks for all the work already done. 

Scott

**Comment by electricjones** [comment]
Thank you. It makes me sad, too, but I've just got to prioritize.

**Comment by smolinari** [comment]
BTW, I can't do too much on the coding side (yet), but I can oversee the repo for you, if you'd like.

Scott

**Comment by dmill-bz** [comment]
Sad to hear but I totally get where you're coming from. Good luck with everything. Hopefully things work out on my end when my company hires a few people towards September. The I'll be able to find more time for this project.

**Comment by electricjones** [comment]
I'm still going to keep an eye on things. If development picks up and I find myself with some time, I may hop back in as a contributor. Good luck with your company.

**Comment by dmill-bz** [comment]
BTW do you guys know any good php devs that may be free for some work? Related to the Yii2 framework. 

Let me know thanks!!!
