### ISSUE TITLE
Transfer repo

### ISSUE THREAD

**Issue by coderholic** [spider/spider#133]
Hi - you mention in the README creating an issue about transferring ownership of this account - I'd love to take it over!

**Comment by electricjones** [comment]
Sorry, I don't know why this didn't ping me. I'm happy to transfer it to you if you still want it @coderholic

**Comment by electricjones** [comment]
I'll keep a closer eye on this issue. Confirm you want it and I'll transfer the organization to you :)

**Comment by coderholic** [comment]
@electricjones yeah still interested!

**Comment by electricjones** [comment]
Okay, I invited you as an owner. Once you are in, I may stay on for a bit just to answer question or whatever. But I'll probably bow and and let you run with whatever.

I'm curious, are you intending to continue with the project in some way or do you want the organization name for something else?

(Either way it's yours. I'm not using it and hate squatters)

**Comment by coderholic** [comment]
Thanks @electricjones! 

Org name for another spider project.
