### ISSUE TITLE
Consistent terminology

### ISSUE THREAD

**Issue by electricjones** [spider/spider#15]
In order for things to be consistent, I propose we adopt a standard lexicon for certain things like properties, fields, and credentials.

When possible, let's rely on TinkerPop definitions, since they are more standard.

It is also worth noting that the `Commands\Builder` is modeled after OrientDb's SQL.

Refer to [Wiki page](https://github.com/spider/Spider-Graph/wiki/Consistent-Terms) for collaboration. Once these things are decided upon, we can refactor.

**Comment by dmill-bz** [comment]
This looks ok. Lets keep property cardinality in mind at this stage (maybe that's more of a `Schema` issue though).
The `credentials` could simply be called `configuration` for the driver. I guess this depends in part on what is decided regarding #13.

**Comment by electricjones** [comment]
Agreed, stick with configuration everywhere. Wiki updated

**Comment by electricjones** [comment]
I will work through this after the #20 merge

**Comment by dmill-bz** [comment]
I'm almost done :)

**Comment by electricjones** [comment]
Moved to documentation and done.
