### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by dmill-bz** [spider/spider#17]
Spider should have it's own set of exceptions. (so we can for example convert the Exceptions thrown by the drivers). 
What Exception classes should we add to Spider?

Here are some ideas:
- [ ] `InvalidConfigurationException` - would this be the same as `ItemNotFound` thrown by `Manager`? or for a user who tries to set a `bool` config as a `string`?
- [x] `FormattingException` - If requesting a format not registered. Let's use a registration system to add formats so it can be extended.
- [x] `ServerException` - would this include all server errors? (invalid credentials, no db found, etc?)
- [x] `ConnectionNotFoundException` - already exists. if a non-existing connection is `make()` by the Manager
- [x] `InvalidCommandException` - if the Command or CommandBag is corrupt.
- [x] `NotSupportedException` - For cases where functionalities in some graph DBs aren't supported (transactions?)

Any other ideas? Also what extra functionality do we want to attribute to these (if any)

**Comment by electricjones** [comment]
Tossed in some thoughts. Can't think of any extra functionality.

**Comment by dmill-bz** [comment]
checked some of these as they are in the PR #20

**Comment by dmill-bz** [comment]
For `ServerException` should we get the drivers to catch all the server exceptions thrown by the clients and return this one exception. Or should we let those stay as they may be more explicit (at least during development)

**Comment by electricjones** [comment]
During development, I want to see the client exception. Maybe later we can have them catch and wrap or something.

**Comment by electricjones** [comment]
What do we want to do with this issue? Move it to documentation?

**Comment by dmill-bz** [comment]
Yeah we've done most of it. And what's left we can just implement as we need them. Worst case scenario we make two PRs with the same added Exception but that's an easy conflict to resolve.
