### ISSUE TITLE
Add insert, update, and delete to CommandBuilder

### ISSUE THREAD

**Issue by electricjones** [spider/spider#18]
Following basic CRUD structure, we have a simple "R" in `$builder->select()`. It's time to work on "CUD".
#### Create

The insert is executed by insert() and insertAndReturn()

``` php
$builder
   ->into($target)
   ->insert(['property' => $value, 'another' => $value]); // no return

$builder
    ->into($target)
    ->insert([
        ['property' => $value, 'another' => $value], // First record
        ['property' => $value, 'another' => $value]  // Second record
]);

$builder
    ->into($target)
    ->return()  // Returns a `SpiderResponse` with the newly made object
    ->insert($records);

$builder
    ->into($target)
    ->return($specificProp)// returns only the specified property (like id)
    ->insert($records);
    //->insertAndReturn($records, $specificProp) is an alias for fluency

$builder
    ->into($target)
    ->return(['prop1', 'prop2'])
    -insert($records);
// returns a `SpiderResponse` with id, meta, label and specific properties)
```
#### Update

Updates are executed by the same methods that execute retrieval (all, first, one, etc)

``` php
$builder
    ->update('name', 'chris')
    ->record($id)
    ->first(); // Updates only one record, returns nothing

$builder
    ->from('users') // from and into are aliases
    ->where('birthday', 'apr')
    ->update('birthday', 'April')
    ->all(); // Updates all apr bdays to April
```

And the same method as insert to return updated records: `updateAndReturn()`
#### Delete

Deletes are executed by the same methods that execute retrieval (all, first, one, etc)

``` php
$builder
    ->delete()
    ->record($id)
    ->first(); // Deletes only one record, returns nothing

$builder
    ->from('target')
    ->where('birthday', 'apr')
    ->delete()
    ->all(); // Bye bye april birthdays
```

And the same method as insert to return records prior to being deleted: `deleteAndReturn()`

**Comment by electricjones** [comment]
This is using the `CommandBuilder`. 

Models will behave more like we would expect (`(new User([])->save())`) and will be built upon the `CommandBuilder`

**Comment by electricjones** [comment]
CommandBuilder updated at branch `cud-command-builder`.

Waiting on refactor of OrientCommandProcessor

**Comment by dmill-bz** [comment]
Quick question, What does the into stand for here?

**Comment by electricjones** [comment]
it's an alias for target. As in `insert($data)->into($label)`

I am rebasing the branch with develop now.

**Comment by electricjones** [comment]
Closing this. See PR #25
