### ISSUE TITLE
Add Traversals and nested queries to CommandBuilder

### ISSUE THREAD

**Issue by electricjones** [spider/spider#19]
Once the basic `CommandBuilder` is up and running, it's time to play with relationships, edges, and graphs :)

Following a declarative paradigm, the user should _describe_ what all they want and have it returned.
### Examples

Here is a query that returns a nested set of
- The first user named "michael"
- michael's friends who have been friends longer than 3 years, only selecting their username and country

``` php
$query->select() // indicates read, select *
      ->from('users')
      ->where('username', 'michael')
      ->limit(1)
      ->where([
          'out' => ['where'=>[['label', 'friends'], ['years', '>', 3]]], // alias to outE(). Also in() and inE()
          'only' => [['username', 'country']],
          'store' => 'b'
          ]
      ])
      ->return('b') // return() by itself returns last stored
      ->tree();
```

Returns

``` js
{
   'username': 'michael',
   'country': 'USA',
   'nickname': '...' // and whatever other properties users have
   'friends': [
       {
          'username': 'eliza',
          'country': 'Spain'
       },
       {
          'username': 'jon'
          'country': 'England'
       },
       // etc
   ]
}
```

**Comment by dmill-bz** [comment]
I'm not sure about calling the link "friends" I think this is something that will need to be viewed while discussing how Tree works.

**Comment by dmill-bz** [comment]
Decided I'd talk about `Tree` here.

There are several levels to this.

**`Response` layer**

Returning the following:

```
'friends': [
       {
          'username': 'eliza',
          'country': 'Spain'
       },
       {
          'username': 'jon'
          'country': 'England'
       },
       // etc
   ]
```

Could be an issue for several reasons. The main ones being that there is no guaranty the user will input the Edge label. They might just want to follow all outgoing edges. Or they might specify multiple labels to follow. 

I feel that the cleanest way to implement this is unfortunately a little verbose. And it would be this : 

```
{
   'object' : 
   {
      'username': 'michael',
      'country': 'USA',
      'nickname': '...' // and whatever other properties users have
   },
   'children':
   {
       {
          'object':
          {
             'username': 'eliza',
             'country': 'Spain'
          },
          'children':{}
       },
       {
          'object':
          {
             'username': 'john',
             'country': 'England'
          },
          'children':{}
       },
       // etc
   }
}
```

The "object" would essentially be a `Spider\Base\Collection`.

**`Model` layer**

Here it would be best to let users define their own relations between models. Which begs the question. Should we introduce a `with()` method to the query builder (not the command builder).

You could define a `friends` relationship in a Model and then do $query->select()->blabla->with('friends')->all().
And that would return a model where `$model->friends` give you a set of the friends.

**Comment by smolinari** [comment]
I like the method chaining, but I find the graph traversal part 

```
  ->where([
      'out' => ['where'=>[['label', 'friends'], ['years', '>', 3]]], // alias to outE(). Also in() and inE()
      'only' => [['username', 'country']],
      'store' => 'b'
      ]
  ])
```

a little less...um....clean (for lack of a better word). And, unfortunately, I also don't currently have a suggestion on how to make that part of the "command" look cleaner. 

Scott

**Comment by dmill-bz** [comment]
@smolinari Theres a bit more on this topic in issue #7 . The gist of it is that other options while less verbose have other issues. 
What Michael placed inside the `where` clause here was an array form of a `Query`. You could very well place a `Query` inside the `where` clause if you wanted.

Anyways, that issue has more information on the other option for traversal which was a more imperative approach, and the shortcomings of using a query builder like that. 

Another post on imperative vs declarative languages is in issue #3 and you can read more on the topic in general here: http://latentflip.com/imperative-vs-declarative/

Many thanks for your insight and feedback it's really appreciated :) 

---

On a side note. I think it would be good for Spider to also support imperative traversal query building in the future. Creating the `GremlinProcessor` will probably involve making a `GremlinBuilder`. We could open that to the users who could use it against DBs that support gremlin (probably all TP enabled DBs, OrientDB, Neo4J, Titan, etc.).
It could serve as an alternative if really required, like with very long traversals.
Just a thought.

**Comment by electricjones** [comment]
Now that we have divided the Command builder into multiple parts, my thought would be to include declarative querying in the BaseBuilder and then add some sugar and/or imperitive building on top of that in the CommandBuilder. The Query is still just the CommandBuilder with dispatching and formatting capability.

There is just something really intuitive about

``` php
$query->select()->from('users')->with('out', 'friends')->depth(3)->all();
```

There is also a further layer of abstraction in the `Model` which has yet to be discussed. Laravel manages relationships in the model by adding methods to the models that allow you to simply do

``` php
User::id(4)->withComments();
```

Something similar would be beautiful

**Comment by dmill-bz** [comment]
That definitely sounds like it could work. Maybe this instead:

``` php
$query->select()->from('users')->out('friends')->depth(3)->all();
```

See why I would rather avoid `with()` bellow:

As for the `Model` abstraction, that's what I meant when I mentioned the model layer `with()`. 
I think it might be interesting to ditch the `withComments()` syntax in exchange for `with('comments')` as this could allow us to do something along the lines of
-  `with('comments.users')` using dot notation to fetch relationships of relationships (this would not return the comments though)
- `with('comments', 'comments.users')` This would return the set with both comments and users who commented.

``` php
User::find(); 
User::findByPk(4);
// etc..
// Would return Query objects hence why we wouldn't want to use with() in the Builder.
```

**Comment by smolinari** [comment]
@PommeVerte - Thanks for the link and info. 

IMHO, I like this better. 

`$query->select()->from('users')->with('out', 'friends')->depth(3)->all();`

As a person from the "outside" and not near an expert on all this, I can understand the argument to avoid `with()`, however, I personally like it better simply because it seems more elegant to me to describe the relation. It simply sounds better/ makes more sense. 

The next question in my mind is how to elegantly do the projection of fields retrieved from the friends.  

Scott

Also, let's say I don't want all the fields in the user vertex coming from friends, how is projection done for the data found with the traversal? 

Scott

**Comment by dmill-bz** [comment]
@smolinari I hear you. `with()` implies getting the result set and the relationship whereas `out()` could simply be a traversal.

And the point you bring up about getting fields and not entire vertices/edges is valid. It would probably fall within the boundaries of passing some information to `select()`. Or the other way of thinking about it is in purely imperative in which case you would have `with()->depth()->properties('name', 'age')->all()`

In any event there's a lot of thinking to do around the imperative->declarative.

``` php
$query->select()->from('users')->with('out', 'friends')->depth(3)->all();
```

Isn't even really semantically correct. It should be : 

``` php
$query->select()->from('users')->with('out', 'friends')->depth(3)->tree();
// what would this even return?
// users.friends.friends.friends
// or 
// users.friends (with all three levels)?
```

So this is going to be a little tricky.

**Comment by electricjones** [comment]
I was suggesting `withComments()` as a simple magic method wrapper for `with()`, but we can ditch that. I'm not married to it.

I am torn on `with()` in the Query Builder. Most relational db orms include a `with` method, and so I was thinking it would make an easier transition. People just aren't used to `out()` ing everything. But, I would be okay with putting the `with` into the Model abstraction and keeping the Query builder with `out`.

@smolinari projections are one of the reasons we decided to go with a declarative, subquery approach. The idea being that you can specify all sorts of filters, projections, and groupings for each "out".

For the above, you may be looking at something like:

``` php
$query->select()->from('users')->with([
     'out' => 'friends',
     'where' => ['place', 'UK'],
     'limit' => 3,
     'only' => 'name, place, occupation' // and always id, label and meta
])->tree();

// Or more likely in the Query Builder
$query->select()->from('users')->out('friends, [
     'where' => ['place', 'UK'],
     'limit' => 3,
     // etc
```

The Model could then use `with` and even predefine relationships like Eloquent and Propel do.

**Comment by electricjones** [comment]
@PommeVerte You are right. `with` implies getting the user _and_ friends. Where as `out` implies starting at a point, traversing, and only returning the destination (only the friends).

I would like to stick with declarative as much as possible with some imperative sugar, maybe.

My main concern is _fluency_ (I like code that tells stories) and a relatively easy _transition_ from the Document or Relational database worlds. A perfect transition won't be possible, and documentation will play a big part in that.

Also, I noticed that my above example should end with `tree()` probably and had no `where` constraints, so it would actually return **all** users and their friends to three levels (potentially a huge query)

**Comment by smolinari** [comment]
```
`$query->select()->from('users')->with([
     'out' => 'friends',
     'where' => ['place', 'UK'],
     'limit' => 3,
     'only' => 'name, place, occupation' // and always id, label and meta
])->tree();`
```

This isn't so bad either actually. 

One thing too. The limit => 3 is for the levels of the branches in the tree? Correct? Wouldn't "level" be more semantic for that? Or maybe even depth?

```
`$query->select()->from('users')->with([
     'out' => 'friends',
     'where' => ['place', 'UK'],
     'depth' => 3,
     'only' => 'name, place, occupation' // and always id, label and meta   
])->tree();`
```

**Comment by electricjones** [comment]
No, limit is for the number of records to return. In this case, it only returns 3 friends.

If we're talking depth of traversal, I like `depth()`.

This is going to require a lot of documentation.

We also should remember that we have three abstractions for `Builder`. A `BaseBuilder` which is verbose, ugly, and efficient. A `Builder` with all that lovely sugar that makes the api fluent and semantic, and a `Query` that is all the above and can dispatch commands and format responses.

So, we can make the `BaseBuilder` verbose and really get all our functionality down and then figure out how to make it a more pleasant api in the `Builder`

**Comment by dmill-bz** [comment]
I totally agree.

**Comment by smolinari** [comment]
> No, limit is for the number of records to return. In this case, it only returns 3 friends.

Ah. Ok. But, to me, `limit()` would make more sense outside the "with" method, since with is for the relationship part of the query, correct?

I also agree with the base/builder/ query concept. :smiley: 

Though I also realize I have no real cause or clout to say anything about what you gents are doing here. Still, I am very, very interested in the work and the resulting library and, I'll do my best to help where I can, to earn the right to have any say in the matters here.

Scott

**Comment by electricjones** [comment]
Your opinion matters because you are an example of our end user. So, especially on the issues regarding API design, please chime in.

**Comment by electricjones** [comment]
On the topic of trees.
1. What if we actually returned an instance of `Tree` which extended `Response` which extends `Collection`. That would leave us open to add helper methods like `collapse()`, `addChild()`, and so forth.
2. If we are using Tinkerpop when possible to form a baseline, and since tree queries are not native in either Orient or Neo4j (that I can find), I vote we mimic gremlin's tree formatting. 
   - https://github.com/tinkerpop/gremlin/wiki/Tree-Pattern
   - https://github.com/tinkerpop/gremlin/wiki/Gremlin-Steps (most of the way down)
   - https://groups.google.com/forum/#!topic/gremlin-users/9s2YWsqK_Ro
   - http://tinkerpop.incubator.apache.org/docs/3.0.0.M8-incubating/#tree-step

**Comment by dmill-bz** [comment]
There's a catch here in that java allows for `HashMap<Object, Map>` which we can't reproduce in PHP. Essentially we can't have an array with an object as a key. It's similar with the Json format passing the information back from the DB.
The original suggestion I made here is how Tinkerpop's (v2) JSONSerializer used to output the data (verbose, [key => object, value=> array]). It's also the discussed format for Tinkerpop3's tree() format.

I do like the idea of providing a `Tree` object. Goes in the direction of providing a `Graph` object later on.

As far as neo4j goes, it is capable of returning a tree in the format of a path (kinda). Some extra logic could make this function in a similar manner to how gremlin works.

**Comment by electricjones** [comment]
It is also possible to return trees using Orient's TRAVERSE. It's just a matter of wrangling everything around. And, honestly, it would be easier to devise a query if we knew what format we wanted returned.

I like that format. It's describable and we can use the `Tree` class to navigate it with helpers if needed.

Can you post a sample tree output in php, just so we have a frame of reference.

**Comment by dmill-bz** [comment]
I would say something along these lines : 

``` php
[
   [
      'object' => Collection, // vertex/edge/property
      'children' => [
          [ 'object' => Collection, 'children' => []],
          [ 'object' => Collection, 'children' => []],
          [ 'object' => Collection, 'children' => []],
          [ 
             'object' => Collection,
             'children' => [
                [ 'object' => Collection, 'children' => []],
                [ 'object' => Collection, 'children' => []],
                [ 'object' => Collection, 'children' => []],
             ]
          ],
          [ 'object' => Collection, 'children' => []],
      ]
   ],
   [ 'object' => Collection, 'children' => []],
   [ 'object' => Collection, 'children' => []],
   [ 'object' => Collection, 'children' => []],
   [ 'object' => Collection, 'children' => []],
]
```

**Comment by dmill-bz** [comment]
Made a quick update to that to show multiple starting points.

**Comment by dmill-bz** [comment]
As Far as the object goes we could also imagine this as a `Tree` inside a `Tree` inside a `Tree`. Each with their own `getLeaves()` etc.. type methods.. Just an idea, I know this is how TP handled trees.
Though this might generate too much overhead for just a Driver level response.
