### ISSUE TITLE
Top Level Spider API

### ISSUE THREAD

**Issue by electricjones** [spider/spider#22]
The `Connections\Manager` served its purpose once, but now that so much more is going on, it needs to be refactored into the top-level `Spider\Spider` as a convenient place to store all configs, create and cache whatever objects (drivers, builders, connections, processors, etc), and hold helpers and utilities.

These are all rough thoughts

``` php
// You may set global configuration
Spider\Spider::setup([
  'default' => 'gremlin',
  'connections' => [ // I don't like this term. This is a package of driver, processor, and credentials
    'gremlin' => [
        'driver' => 'Full\Class\Driver',
        'processor' => 'Full\Class\Processor', // or use convention, which I think I'd prefer
        'hostname' => 'localhost' // and the rest of configurations    
    ],
    'gremlin-two' => [
        'driver' => 'Full\Class\Driver',
        'processor' => 'A\Different\Full\Class\Processor'
        'hostname' => 'remote' // and the rest of configurations    
    ],
    'orient' => [
        'driver' => 'Full\Class\Driver',
        'processor' => 'Processor'
        'hostname' => 'remote' // and the rest of configurations    
    ],
    // etc
])

// And then make a new instance
$spider = Spider::make(); // default by default
$spider = Spider::make($connection);
$spider = new Spider($config);

// The returned Spider object extends the CommandBuilder and contains the correct connection, so you may use the querybuilder directly
$spider->select()->where()->get();

// Or return its pieces
$spider->getDriver();
$spider->getProcessor();

// Or make new instances of components (eventually includes)
$spider->connection(); // returns a new connection from config, alias, or empty
$spider->graph(); // returns a new empty graph (model) with current connection
$spider->schema(); // returns a schema builder with current connection
$spider->make(); // makes a new Spider with current connection
$spider->reset(); // destorys current spider and makes a new one
```

**Comment by electricjones** [comment]
On this note, we may be able to lose `Connection` all together. All it really does now is pass things through to the driver. I had included it to leave some wiggle room for the future, but I don't remember what I had in mind and now I cant think of a reason to have a middle-man connection.

**Comment by dmill-bz** [comment]
Connection could handle Transactions (simulating nested transactions), query caching, load balancing in some cases. etc.. I think we should keep it. 
I'll have a bit more time to look at the PR tomorrow :)

**Comment by electricjones** [comment]
Sounds great.

**Comment by electricjones** [comment]
Have begun a very work-in-progress top-level Spider api in branch `spider-api` with the following goals:
- [x] General Global setup `Spider::setup()`
- [x] Use the querybuilder directly
- [x] Spider factory to produce connections and querybuilders from configuration
- [x] Introduce an IoC container for dependency management (specifically for things like caching, logging, and events)
- [x] Lay the foundations for system-wide events, cache, and logging based around generic interfaces. All components swappable. Just lay the foundation. Not actually add those calls inside driver, etc yet.
- [x] Keep up to date with documentation.

I have some time this week, so I want to get a nail in this and some further work on traversals inside the `BaseBuilder`.

**Comment by electricjones** [comment]
No need for review yet unless your bored. I'll call for a review when I've got something a bit more. And, of course, this will wait until after the 0.3 release.

**Comment by dmill-bz** [comment]
Sounds great, I'll have a look at some point. I'm almost done with the cypher processor and have some suggestions for traversal implementations which should make the dev really quick (I hope, fingers crossed). 
I would also like to see if I can't drum up a quick gremlin processor so we can keep an eye on all fields as we move forward.

Related, I've made a few changes to the `Bag` and some more to the `BaseBuilder` so you might want to wait for those to hit develop before implementing traversals. 
It might be wise to also make sure we get near 100% code coverage on the processors and builders before complicating everything (to avoid regressions)

Aaaaaand while I'm at it. I've been thinking that we should provide a `TraversalBuilder` that extends `BaseBuilder` with a traversal syntax. I know we originally wanted to add sugar to Builder for this but thinking about it, it will be too complicated to do something clean (overlap and conflicts between what some methods would do). I have a couple of ideas here as well.

**Comment by electricjones** [comment]
so then, would `Query extend Builder extend TraversalBuilder extend BaseBuilder`?

I like that separation. But I think we can still use `Builder` solely as a sugar class and `Query` solely as a dispatching class. I'll hold off on traversals for now. Plenty of other things to keep me busy :smile:

**Comment by dmill-bz** [comment]
Oh I didn't think about `Query`. `Builder` and `TraversalBuilder` would have been two leaves (it's not possible to have it function properly any other way as all the methods would function differently in populating the Bag) so maybe that would imply a different Query class as well.

**Comment by electricjones** [comment]
I don't think I like that. Which methods would conflict? Especially if we are are approaching the builder in a declarative way.

I'd much rather add the basic traversal features to `BaseBuilder` so it can:
1. CRUD vertices and edges with labels and types (already implemented)
2. Manage relationships between vertices (`$builder->addEdge($from, $two, $label, $properties` or something)
3. Perform basic relationship queries (get all friends of user 3 who have been friends more than 2 years, or get all posts tagged as new and important, etc.)
4. Perform powerful, if verbose queries, sub queries, and traversals. This would be 
        \* "find shortest path between x and y
        \* Get all users friends to three levels from the users whose favorite color is purple, also get the last three comments tagged as "new" from each of those users.

I can definitely see the benefit of adding the last one into its own class or trait (probably class). But, then, `Builder` would simply extend the above and provide some sugar-fluent syntax to make life easier. `Query` would only add dispatch methods.

However we decide to separate the logic, it's probably best to open an issue with these kind of BDD examples for each class so we know exactly where the responsibilities lie.

**Comment by dmill-bz** [comment]
I think a lot of what you mention would probably be better on the `Model` layer. It's an abstraction on the logic (query construction) and not really query sugar. 

Also all methods would conflict.

``` php
$builder->out()->out()->where().
```

The `where` here would have to function completely differently to the current where that just adds stuff to the bag since this where would need to apply to some sub query. Actually a lot would have to be happening in the above. Anywho I don't see a `where()` or many other methods working for both scenarios.
Also what happens if you use `out()` in a declarative scenario? Sounds like a headache waiting to happen. I don't think there's much harm in providing two builders, two queries is a bit more of an issue though.

**Comment by electricjones** [comment]
I think the issue here isn't traversals vs crud, but imperative versus declarative. If we stick to declarative and use orient sql and/or cypher as our guide (both declarative), then it should be manageable.

I don't mind creating a second query for imperative queries down the road.

**Comment by electricjones** [comment]
It is true that most of that logic is better executed from a Model, but the model still communicates through the builders, so the builders have to be able to do this, even if it is ugly.

I don't mind two builders. Its the two queries that rub me the wrong way. It complicates things for the user having to choose between or carry two different objects around in their code. This may be simplified in the top level api like

``` php
$spider->traverse($start)->out()->out()->with();
$spider->query()->select()->from();
```

But that still seems unwieldy.

Having two builders also makes it difficult for a higher abstraction (model) to know which builder to use without being explicitly told. At the end of the day (top-level), the user shouldn't have to make that choice. They should declare what they want from a `model` or `spider` and it happens.

If we use subselects (as orient sql does), then most of the above is possible (with the exception, maybe, of number 4. I'd have to ask around).

**Comment by dmill-bz** [comment]
Yeah we can worry about traversals at a later point. Once we have the rest down. 

As for the model vs builder logic. The `addEdge` scenario doesn't really properly represent the whole abstraction layer. Imagine instead a `reattachEdgeOut` that would reattach an outer end of an edge to another vertex. This task needs to remove the current edge and add a new one and needs to be done within the scope of a transaction in case the edge adding fails. This is way higher logic than builder alone. 
The idea is that the `Model` methods would build the appropriate queries via `Query` or `Builder` and submit them (using delete and insert which are already quite straightforward).

**Comment by electricjones** [comment]
I see what you mean. I think we are saying different things by "traversal" I had thought you meant, really, any graph functions (managing edges, querying related records, etc). I am going to open another issue "Builder and Query Responsibilities" where we can discuss exactly how to divide this.

**Comment by electricjones** [comment]
I just pushed to `spider-api` branch. It now contains the unified api and resolves #29. You can set general configuration at the `Spider::setup()` level and it trickles down through the system.

Added a `Base\ThrowsNotSupportedTrait` so classes can simply `$this->notSupported($message)` and it will be handled based on configuration, defaulting to fatal.

Removed the IoC container and system-wide events and logging. Belongs in a separate branch and no need to crack that egg yet.

While these all pass, I'm sure the PRs will break them. No need to dig in until 0.3 is released and all this is rebased. Just wanted to finish my thoughts.

**Comment by electricjones** [comment]
I updated all this with the 0.3 release. The top-level api:
- [ ] Holds static configuration
- [ ] Builds a spider from connection credentials
- [ ] Extends the QueryBuilder (this may change depending on how we split the builders)
- [ ] Each instance has factories to produce connections, querybuilder, and (in the future) other components (models, schema builders, fixtures, etc)
- [ ] Drivers updated with a `ThrowsNotSupportedExceptionTrait` that allows for `$this->notSupported($message)`. If the driver was handed a `Manager` object with configuration, the error will be handled either `silent`ly, `fatal`ly with an exception, or `quiet`ly with a warning. We can change these terms and should probably use constants somewhere, anyway.
- [ ] And, of course, adds tests, docs, and passes current tests.

Just a first draft, really.

**Comment by dmill-bz** [comment]
I've been meaning to look at this. (I will get there eventually) 
Are we going with dependency injection or some scoped global configuration (ie: static class property)? 
I'll elaborate after taking a look at what you set up and offer some alternatives to make sure all bases are covered (not that we would need the alternatives, but just to make sure we have it all covered).

**Comment by electricjones** [comment]
I have a dependency injection container branch that branches off of this one I was using for system-wide,  swappable integrations (like event dispatcher, logging, etc). I can push that branch.

I am not a fan of static global configuration touched by anything except the static object. That is, I don't like something like `Query` being able to arbitrarily reach into `Spider::$setup` for configuration.

Instead, I figure that you setup `Spider::setup($config)`, make the instance `Spider::make()`, and then use factories off of the instance if you need to. The `$spider` passes config objects into the constructors of the other components (like query builders or connections).

The only advantage to having _any_ static configuration is the ability to create spider objects from different, preset connections:

``` php
Spider::setup($config);
$spider = Spider::make(); // Makes a spider with default connection
$spider = Spider::make('another-connection'); // Makes a spider with a different stored connection
```

**Comment by electricjones** [comment]
The inspiration for most of this comes from Laravel's Database Component: https://github.com/illuminate/database

I feel like that wasn't terribly clear. Here it is step by step, with the addition of system-wide integrations and dependency injection.

The user sets up global configuration:

``` php
Spider::setup([
    'connections' => [
        'default' => 'neo',
        'neo' => [
            // credentials
        ],
        'orient' => [
            // credentials
        ],
    ],
    'errors' => 'fatal' // set NotSupported errors to be fatal
]);
```

Now, the user instantiates a new spider object:

``` php
$spiderNeo = Spider::make();
//or a specific connection
$spiderOrient = Spider::make('orient');
```

With that $spider, the user can dig straight into the querybuilder.
Or, they can create configured components:

``` php
$connection = $spider->connection(); // create a new default connection
$connection = $spider->connection('orient'); // create a new orient connection
$query = $spider->querybuilder('orient');
// And eventually
$model = $spider->model('neo'); // for a generic model
$schema = $spider->schema(); // for a schema builder
$fixture = $spider->fixture(); // for a fixture loader
// and on and on we go
```

What's happening behind the scenes is that `Spider::setup()` is only storing config into a static property.

When the $spider is created, it is built and configured from that configuration if it exists. If it does not exist, defaults are used. And, of course, defaults cascade. There is no default for connections, the user must set those.

The user also (eventually) has the ability to swap out integration components:

``` php
Spider::setup([
    'integrations' => [
        'events' => 'My\Event\Dispatcher', // that implements the interface
        'events' => function () {}, // returns an event dispatcher
        'events' => new EventDispatcher(), // for eager loading
        'events' => $manager, // an instance of ManagesIocItems which has a fetch() method
    ]
]);
```

Now, instead of the default event dispatcher being passed into the Connections, Drivers, Builders, and such, the user-supplied one is. You can look at chrismichaels84/data-manager branch `dependency-injection` for options.

This also gives us a simple ioc container to use.

However, if the user just wants to use the components, there is no need to setup the global configuration. They can just `new Connection($credentials, $config, $events, $logger, $etc)`. Credentials is all that is required. If the others are missing, either defaults are assumed (for config) or no events are fired, no logs saved, etc. I have laid the groundwork for this, but not fleshed it out (though it shouldn't be difficult). I didn't think this was needed now, but I can bring it to full life pretty quickly.

**Comment by electricjones** [comment]
I was half-way through the integration swapping and ioc container when I realized I was jumping the gun. It's sitting on my local machine, just collecting dust.

**Comment by smolinari** [comment]
The post above the last looks a lot like spec documentation along with some not quite clearly identified UAC to me. :smile: I've seen other projects that use this approach for development. For instance, they use the task lists for the UAC's. I'll explain in an example. 
- [ ] The user MUST add configuration in a configuration file in `/some/directory`.
- [ ] The configuration MUST be in the following format.  

```
Spider::setup([
    'connections' => [
        'default' => 'neo',
        'neo' => [
            // credentials
        ],
        'orient' => [
            // credentials
        ],
    ],
    'errors' => 'fatal' // set NotSupported errors to be fatal
]);
```
- [ ] The user MUST be able to instantiate the spider object with a static `make()` method.

```
$spiderNeo = Spider::make();
```
- [ ] The user CAN instantiate the spider object with a specific driver as a parameter for `make()`, which will override the configured default driver. 

```
$spiderOrient = Spider::make('orient');
```

etc. etc.

Scott

**Comment by smolinari** [comment]
And a question for my understanding. Is there actually a need to use two different graph databases within a single project? What would be the use case/ reason for this?

Scott

**Comment by dmill-bz** [comment]
Yes there can be many reasons to do so. Some graph DBs might provide better features for some specific tasks while another is better for something else. though to be honest I think it would mostly be a case of having a graph DB and some other storage system such as ES or MYSQL on the side (which we can cover with appropriate drivers). Though to be honest I've never seen a case where a model needed to be used with several DBs. Models tend to be task specific (and tasks are db specific) so they don't mix much.

The dependency injection model is fine by me because it should be able to work in most integration scenarios (most of the painful aspects of carrying the dependency container around can be abstracted in whatever application is being built) but how about these cases: 
- How do plugins interact between each other?
  For example the NotSupported cases:
  - setup spider with a main neo4J db and a mysql db for side work.
  - set it `errors` to `log` rather than `fatal`. And if I want to configure a different logger for the entire application (log into mysql for example). Is the following sufficient considering the Trait?
  
  ``` php
  Spider::setup([
    'connections' => [
       'default' => 'neo',
       'neo' => [
           // credentials
       ],
       'orient' => [
           // credentials
       ],
    ],
    'logger' => [
       'class' => '\Some\New\Logger',
       'db' => 'neo'
    ],
    'errors' => 'log' // what here? Is it automatic?
  ]);
  ```
- In MVC environments how to you pass `Spider` around? It seems like you would have to recreate it in each section (or use a global static class property). Any cases where multiple instances of `Spider` would be detrimental? (several sockets being used for a single page load for example)
- In the event of having to use multiple instances of `Spider` I'm guessing the cache can't be shared between them? (see above). 

Not saying we should worry or cover these scenarios but we need to keep them on the radar.

**Comment by smolinari** [comment]
> some other storage system such as ES 

Oh yes! This is exactly what we'll be needing too! OrientDB with Elasticsearch. And, I am absolutely certain any other application needing serious search indexing would need it too, because the DB search/ indexing facilities are simply too limited.

Scott

**Comment by dmill-bz** [comment]
@smolinari Have you considered using Titan? It can be set up to use Elastic Search as one of the indexing backends. Would be much more efficient than using two systems. It also has support for vertex centric indices and other nice features for large data sets. (that neither neo or orient support yet)

**Comment by smolinari** [comment]
I had glanced over Titan, but I couldn't find PHP driver support, so I passed it by. I do like the looks of Titan for sure. 

Scott

**Comment by smolinari** [comment]
Ahh! But lo an behold, https://github.com/PommeVerte/gremlin-php

How efficient is using Gremlin server between Titan and PHP?

Scott

**Comment by dmill-bz** [comment]
Well communication with gremlin-server is done through the websocket protocol. So you can use that as a reference on communication speed between php and titan.

**Comment by smolinari** [comment]
Thanks for the tip. 

And for sure, a websocket is miles better than an HTTP connection. What I meant though is since it is added layer, does it perform slower than say Orient/PHP? Probably something to test later I guess. I am far from making a final decision. 

Oh, and since spider is going to be so resilient, my options are open. ;-) :+1: 

Scott

**Comment by dmill-bz** [comment]
Gremlin server isn't any more of an extra layer than orient server for orient graphs. They both expose the underlying graph Java API. 

Differences in speed if there are any would be related to either the gremlin language or the underlying storage system for Titan (Cassandra for example) but Titan has an embedded mode to remove this

**Comment by smolinari** [comment]
Yes, I am learning more about Titan right now (and the whole graph framework Aurelius is building). It is quite impressive and looks more "enterprise ready" than Orientdb, if my impressions are correct.

Scott

**Comment by smolinari** [comment]
Hey @PommeVerte. Can I add you to my OS org, to chat on Gitter, when you have some time?

Scott

**Comment by dmill-bz** [comment]
Sure go ahead!

**Comment by electricjones** [comment]
Alright, now that I'm home again and chomping at this bit to make more progress, I wanted to respond to @PommeVerte questions about the DI and integrations.

This is how I see it.

For swappable components (events, cache, logging, ioc container), there are simple interfaces. Whenever possible, use standard interfaces (like psr for logging). When that is not possible, make the interface as simple as possible.

We are actually integrating spider into Laravel, so this is what we had planned on doing:

**How do plugins interact between each other?**
- Creating a concrete class for each of the integrations that implements the Spider contract and simply wraps laravel's caching, logging, events, etc utilities.
- Do the same for laravel's ioc container: wrap it in a class that implements the ioc interface. Then, inject that container into Spider at setup.
- The wrapped ioc container is then passed around the different components (Query, Driver, etc)
- So long as each integration (call them extensions or plugins?) implements the interface, the Traits couldn't care less _how_ the logic is handled.

**In MVC environments how to you pass Spider around?**
I don't know about other systems, but Laravel offers a `Container` class that has the ability to use singletons. In that instance, the Laravel Service Provider would create the spider instance on setup, and then you would use the container or a facade to call the same instance each time.

We could also add a light alternative to this in the static `Spider`, some kind of `Spider::getInstance()`

**In the event of having to use multiple instances of Spider I'm guessing the cache can't be shared between them?**
I guess that would depend on how those things are resolved.

The built in IoC container allows users to define these dependencies in four ways:

**As a class name** which creates a new instance each time its called. I can't see why this would be useful for spider, but its part of the `michaels/data-manager` system.

``` php
Spider::setup([
    'integrations' => [
        'events' => 'Some\Events\Class'
    ]
]);
```

**As an instance object** which returns the same instance of the object each time. 

``` php
$events = new MyEventClass();
$events->setup();

Spider::setup([
    'integrations' => [
        'events' => 
    ]
]);
```

**As an instance of the container itself**, which will simple call `fetch($name)` whenever the integration is needed.

``` php
$ioc = new Container();
$ioc->set('events' $object);

Spider::setup([
    'integrations' => [
        'events' => $ioc
    ]
]);
```

Or, **replace the entire ioc** giving you the ability to do whatever you want, really.

``` php
Spider::setup([], $newIocContainer);
```

I'm ironing through the details today and tomorrow, but those are my thoughts.

Are there any other integrations we could need? I don't really want to _create those_, yet, just lay the groundwork while I'm digging around in the ioc container.

Am I missing some glaring problem? I tend to glaze over the obvious some times, lol.

**Comment by smolinari** [comment]
Not sure if it is totally relevant, but I'd like to see it possible to build this kind of bridge for a Spider integration into Symfony. https://github.com/symfony/DoctrineBridge

Scott

**Comment by electricjones** [comment]
That is exactly the kind of bridge we are going to use for laravel. I figured that we (or third parties) could create bridges/integrations that can be hosted in this organization.

Same with drivers. Ultimately, I'd like to see:
- spider/laravel-bridge
- spider/symfony-bridge
- spider/yii-bridge
- spider/mysql-driver
- spider/orient-extensions (to use document features)

And maybe more?

**Comment by smolinari** [comment]
:+1: 

Scott

**Comment by dmill-bz** [comment]
Ok, I'm going to absorb all that information and try to think up some complex user cases and see how they play out (preferably as far away as possible from the usual ioc scenarios). Then I'll get back to you.

With that said I would personally be inclined to avoid giving spider a singleton design pattern (even if optional) as this is really an anti-pattern, it works horribly with Opcode cache which is a huge no-go (I'm not sure about hhvm) and is a bit of a testing smell to boot.

**Comment by dmill-bz** [comment]
given 

``` php
$connection = $spider->connection(); // create a new default connection
$connection = $spider->connection('orient'); // create a new orient connection
$query = $spider->querybuilder('orient');
// And eventually
$model = $spider->model('neo'); // for a generic model
$schema = $spider->schema(); // for a schema builder
$fixture = $spider->fixture(); // for a fixture loader
// and on and on we go
```

How does one create their own model and implement it?

**Comment by electricjones** [comment]
Models are a bit further away, but I pictured three kinds of models (which I discuss in the documentation)
1. explicit models
   Preferable, ActiveRecord Patter. Create a class that extends `Spider\Models\Model'
   `User::all() (new User([]))->save()`
2. or dynamic models `$spider->makeModel('user')` which returns a `Spider\Models\Model` with the label set to 'user'. 

You can then `$model->all()` or 

``` php
$user = $model->create();
$user->name = 'Dylan'
$user->save();
```
1. or generic models `Spider\Models\Model('label')` which is the same as two, just explicitly created.

Obviously number 1 will be 99% of the cases, but (when working with potentially unstructured data), I've been told its nice to be able to create models on the fly. We can look at this further down the road.

**Comment by electricjones** [comment]
If not a singleton pattern anywhere, then how would a user register an event? All the frameworks I've used (laravel, yii, symfony) at least support singletons for these reasons.

I don't like singletons either, but I haven't found a better way to deal with certain circumstances.

**Comment by dmill-bz** [comment]
Well I'm not sure about laravel or symfony but yii's entry script stores an `Application` object in a static property of the Yii class (producing a namespaced global property). Since it's entry script level it is only ever set once and kind of behaves like a singleton but isn't one. 
I wouldn't be surprised if at least symphony/zend worked this way as well as I remember hearing that they (or at least one of those two) were removing singleton design patterns from their code.

**Comment by electricjones** [comment]
So what would you suggest for spider?

**Comment by electricjones** [comment]
Oh, you mean global singletons. No, I wasn't suggesting a global Spider singleton. I may not be using the term correctly. I am suggesting an ioc container that can fetch the same instance of an object (say event object) wherever it is called.

Am I understanding?

**Comment by dmill-bz** [comment]
I see what you mean. And as far as suggestions go I think we should run with everything you've been doing so far. I might try to play this out against a framework like Yii to see how it behaves and then give some feedback

**Comment by electricjones** [comment]
Okay. Be warned: the published branch is unstable. I'll have time to really dig in tomorrow and hopefully come up with a solid working draft for everything. Very open to suggestions.

**Comment by electricjones** [comment]
I am moving this discussion to PR #82
