### ISSUE TITLE
Graphs only?

### ISSUE THREAD

**Issue by smolinari** [spider/spider#28]
Hi,

I am very interested in this project, but will it also support the document API of OrientDB too? What will make it better than this project? https://github.com/doctrine/orientdb-odm

Scott

**Comment by electricjones** [comment]
The difference is that spider comes with several drivers. Currently we are building one for Orient, Neo4j, and Gremlin. So, you can switch between or use multiple graph databases in a single codebase or across several projects without having to relearn everything.

Spider will also be extensible, and I intend to create an extension that will give Spider some orient-specific features for those using it with orient.

Once 1.0 is reached, we should have:
- An awesome query builder with powerful traversal and subquery capability (which odm doesn't support, really)
- A full schema builder that works across graph databases
- Models and an Object Graph Mapper
- databinding, validation, caching, and logging
- be composable so you can use only the pieces you want
- be able to create other drivers (theoretically even for mysql, mongo, or whatever

We are nearing a pretty big pre-release that should show the potential. You can also check out the docs at http://spider-ogm.readthedocs.org/en/develop which I'm writing now.

Also, odm hasn't been updated in a while. It's a great library. This is just an alternative :)

**Comment by smolinari** [comment]
> An awesome query builder with powerful traversal and subquery capability (which odm doesn't support, really)

Yeah, I was thinking it didn't have the graph capabilities, which means your project is even more interesting to me now. It might even (probably will) be a basis for my project. www.skooppa.com

Scott

**Comment by electricjones** [comment]
Cool. Let me be clear. It doesn't have traversals, yet. That should be in the next few weeks. If you have any ideas on API design (how you would like to _use_ traversals), **please** leave a comment on Issue #19.

**Comment by electricjones** [comment]
Moving this discussion to #19
