### ISSUE TITLE
NotSupportedException vs Not supported warning.

### ISSUE THREAD

**Issue by dmill-bz** [spider/spider#29]
I just wanted to bring this up for discussion.

The idea is that some graph DBs are going to support some features while others wont. Examples range from tree functionality to transactions to indexing capabilities.
Now if every DB Driver or Schema implementation throws exceptions on unsupported features, this means that ultimately, switching backends will not be possible without a wave of exceptions being thrown, and code refactor. 

I feel it's our duty to make the transition from one backend to another as easy as possible. Hence the introduction of warnings.

The idea is that if you are using transactions in your app with a transaction enabled GraphDB, and then you decide to switch to a transaction disabled GraphDB, the system will emulate transactions but throw a warning (non thread breaking). Rather than outright throw a thread breaking exception.

Same could be done with creating indexes if it isn't supported, the system just ignores the index creation and throws a warning. (queries etc.. still work they just don't use index optimization)

Some cases like tree however will need to continue throwing exceptions as it would be a potential app breaker.

Thoughts?

**Comment by electricjones** [comment]
I like the idea, but its implementation may be difficult. Even warnings can be a problem in production code. No system is going to be 100% db swappable. Instead, lets try to make it as painless as possible. Say (in most cases), no more than 2hrs work, or whatever.

We will eventually have a top level `Spider` which will hold configuration and be a factory of sorts. What if we gave the option for three levels of warnings:
1. Fatal - every not supported is fatal.
2. Quiet - we produce warnings, probably by catching the exceptions and raising warnings
3. Silent - when possible, no output is rendered. Only logged using the logger of their choice.

Which also raises the issue of logging and caching with third-party packages. Simple interfaces for logging, events, and caching may be helpful. FIGG is working on these, so we can implement them at a time in the future.

There is also the issue of multi-model databases that need to be considered, though in a different issue. For instance, OrientDB has polymorphism in its vertex types (labels) and document db features. There should exist a way for third-party packages to _extend_ Spider for these db-specific features.

**Comment by dmill-bz** [comment]
I agree that all sounds good. As For OrientDB, I know that they are currently working on a TP3 implementation. I'd be curious to see how that works out before moving forward as it may shed some lighting on how to handle these scenarios.

**Comment by electricjones** [comment]
I am going to add this configuration into the top-level api. Issue #22

**Comment by electricjones** [comment]
Moved into #22. Closing conversation here.
