### ISSUE TITLE
Scalar values and collections with a single value

### ISSUE THREAD

**Issue by electricjones** [spider/spider#37]
As it stands, `getScalar()` only works if the database returns a scalar value. Should `getScalar()` also work for a `Collection` returned with a single scalar value?

For instance `$query->select('name')->from('users')->byId(3)` should return only a collection with a name property (and meta). `$results->getScalar()` should return the `string` name.

**Comment by dmill-bz** [comment]
Hmmm I think that a scalar shouldn't be a collection. But a single string sure. I can see the edge case here and it could be a little tricky depending on how orient returns the result.
Gremlin-server and neo should return scalar-ish results to the kind of query you posted so it should actually already work.

**Comment by electricjones** [comment]
No, scalar doesn't return a `Collection`. Scalar only returns a scalar. I'm saying that `getScalar()` returns only the value of the single property in the response.

Orient already supports this, but I've commented out the code to make the driver behave like the others.

**Comment by dmill-bz** [comment]
I see what you mean. I think the difference here is that orient would return that as a collection whereas the other databases would just return that query as a scalar (no such thing as a Collection with a single scalar value in those cases). 
So technically this should already be supported for those DBs.

**Comment by electricjones** [comment]
Oh, I hadn't realized that. In that case, I'll just normalize orient and call it a day.
