### ISSUE TITLE
Should Query::all() always return an array?

### ISSUE THREAD

**Issue by electricjones** [spider/spider#40]
At the moment, I've noticed, that Query::all() will return the response formatted as a set. This could mean either a single `Collection` or an array of `Collection`s.

I believe that `Query::all()` should **always** return an array, even if that array only has one result. This would seem more in line with other orms.

Any serious objections from anyone?

**Comment by dmill-bz** [comment]
none :). I'll try and find some time today to go over the various tasks I've been meaning to do (and check the PRs)
