### ISSUE TITLE
How to handle labels with schema

### ISSUE THREAD

**Issue by electricjones** [spider/spider#41]
So, I get the idea that "label" is a schemaless concept. That is, if you do not designate a label in Neo4j or Gremlin, then the vertex with have no label. Or, that you do not have to create labels in order to assign a vertex to a label.

This is not the case in OrientDB. A "label" is analogous to a Class. If you designate no class then it defaults to "V", but you cannot arbitrarily assign classes. That is, a class must exist before you assign a vertex to it.

What would be the best way of normalizing this? Any thoughts?

**Comment by dmill-bz** [comment]
Very good question. I also don't think there's an easy answer other than rewriting a php version of tinkerpop where each db implementation comes with it's own set of methods. Needless to say this goes way beyond the scope of what spider is. 

The simplest possible way of handling things (which has it's shortcomings) would be to just have spider use gremlin for graph DBs... and only gremlin. That way we can take advantage of all the work already done in this field. 

Short of that there is no realistic other option. Users would have to manually add the labels to their DB migration if they use orient. (Migrations are another thing we will need to add to spider)

**Comment by electricjones** [comment]
I don't know how comfortable I am using gremlin and gremlin only. Mostly because TP3 is still incubating and I'm having trouble, honestly.

As far as I know, Orient is the only one of the three that handles it differently. I would probably rather, at least at this point, handle it with Exceptions that make sure the user builds the correct classes. Not so graceful :(

The other option would be a hit for performance, but the OrientDriver could check if a class exists and create it if not. I _really_ don't think I like that idea, but it is an alternative. Just wanted to start the discussion.

**Comment by dmill-bz** [comment]
Ok how about option 2 then. Where if you're working with orient you have to specifically add label creation to your migration? If you don't orient server will throw an error saying that the labels (classes) don't exist. 

The advantage here is that. It makes sense if you think of labels as indexes (that you would set in your migrations anyways). Migrations will use DB specific Schema classes so we have leverage on handling compatibility issues. For example if Neo doesn't allow creating labels before assigning them to elements then `Neo4jSchema` can just ignore label creation. 
It also keeps the Drivers clean of any unnecessary bloating.

**Comment by electricjones** [comment]
That was my thought. For now, I will add a simple try-catch in the record creation of Orient's Driver. If the user tries to add a label for a non-existent class, I'll just rethrow a more descriptive exception. We can deal with the rest hen Schema's come around.

**Comment by dmill-bz** [comment]
sounds good

**Comment by smolinari** [comment]
Just as a question of interest. 

> but the OrientDriver could check if a class exists and create it if not. 

Creating classes isn't a regular occurrence usually, correct? So, performance wouldn't be hit too badly.

Have you ever worked with Mongo? It doesn't even care if a collection has been created or not. If it hasn't been created, Mongo just creates it automatically and data can be persisted in the collection. This is a great advantage, as schema versions then don't need to be maintained within development (and one of the core concepts of MongoDB). The code maintains the schema. 

Not sure if that is practical or wanted with Spider (with ODB?), but it sure would be cool. I realize too, some people scream for enforced schema in the database. I don't understand why. But, that might be my inexperience talking. Being able to run with an application and not worry about it fitting the database seems so much more flexible to me. 

Scott

**Comment by electricjones** [comment]
Most of the graph databases are totally schemaless. The question I issue I am rolling around in my brain is for the situation where a user tries to:

`INSERT INTO cats CONTENT {name: 'oreo'}`

and the class `cats` doesn't exist. orient troughs an error.

The same in spider
`$query->insert('name', 'oreo')->into('cats);`
would through an error in orient, but not in Neo4j. This inconsistent behavior is what I was talking about.

In either situation, you can create as many properties in a schemaless way as you like. The solution here is probably just to catch, wrap, and let bubble up the server exception. That's my opinion

**Comment by smolinari** [comment]
Exactly. It is this schemalessness of document databases that is an advantage IMHO. The objects created by the code should just be persistable. The objects form the schema alone. If I add a property to a class and want it persisted, it should just happen in the database. The code controls the schema. 

Scott

**Comment by dmill-bz** [comment]
It's odd that orient wouldn't do this by default though. Maybe its worth digging a bit to find why. 

In the case of Mongo, if I recall correctly (I'm not all that familiar with it) it uses a RDBMS with an EAV table so it is somewhat schema-less and trivial to add collections which seems not to be the case with Orient. (But terribly slow because EAV is a definite anti-pattern)

@smolinari what you are suggesting is the try-catch-build_label-resubmit scenario right? This kind of goes along the lines of what @chrismichaels84 suggested by having the `OrientDriver` do this work. But it would be poor design to take care of it on this level. Perhaps a `Model` layer could have a generic try-fail-retry strategy for this scenario.

---

On a side note -yet somewhat related to Orient's mode of functioning being different from other dbs- I've noticed that the following doesn't work for orient:

``` php
$driver->executeReadCommand((new Builder())->select()); // error
$driver->executeReadCommand((new Builder())->select()->from('V')); // ok
```

We might have to look into these inconsistencies at one point.

It doesn't help that I'm not all that familiar with Orient so I'll probably spend more time playing around with it. It just comes across as being a graph DB built around a document store without a comfortable level of abstraction. 
Once they make an implementation for TP3 maybe it would be a good idea to base ourselves on that as it will abstract a lot of these concepts (classes, 'where id' queries, etc..).

**Comment by electricjones** [comment]
Agreed on keeping with TP3 standard. In truth, it may be best for spider to be somewhat of a TP for php. The reason that the above fails in orient is  because there are several predefined classes and that query doesn't say which to pull from (V, E, or Document). I can made "V" default at the driver level so the query failing query would pull all vertices by default.

**Comment by electricjones** [comment]
I think this is good to be closed. I will modify the orient driver to:
- use "V" by default
- catch and rethrow an error if trying to insert into a non-existent class
- Later, in the model layer, that exception can be caught and the class can be created before the record is resubmitted.

I am also going to open an issue with orientdb do see why this is. They are really good about adding new features based on issues. I've had two added already in the space of a few weeks.

**Comment by electricjones** [comment]
Commit 665f337edb44e4ef4f7ba875e591142d17ce1f15 closes both of these

**Comment by dmill-bz** [comment]
Hmm so does this mean that `V` is a label? Can you give me a quick walkthrough of labeling vs classes in orient? 
Can vertices and edges have the same label yet be queried separately? Is this an object hierarchy type system where classes extend V so querying for V returns all children classes?

**Comment by electricjones** [comment]
There are no labels in orient. There are classes, and they really work the same as in Java and PHP (no multiple inheritance).

The base class is `Document`. Built in classes `V` and `E` extend `Document`. Any custom class extends one of these three (V by default, I think).

`Document`s are like Mongo documents, with as many nested properties as you like. They are represented as json documents.

``` javascript
{
    name: 'michael',
    books: ['Lord of the Rings', 'Jack Reacher'],
    cat: {
        name: 'oreo'
    }
}
```

And you may query like `SELECT FROM V WHERE cat.name = 'oreo'`, etc.

Any vertex (that is any document that can be joined by edges) must extend `V`. Edges extend `E`.

So, let's say:
`Person extends V`
`Character extends Person`

If you query V by `SELECT FROM V`, then you will get all `V`, Person, and Character. If you query all `Person`, `SELECT FROM Person` you will get all `Person` and `Character`.

You can even define classes as abstract, which cannot hold records directly, but only be subclassed.

The primary reason for classes is to define optional schema. You can define property fields as datatypes (as you would in RDBMS), and even make some of those properties required.

So let's say that `Person` has set properties `{name, age}`. If `name` is required, then orient will throw an exception if creating a new Person without a name.

These classes may also be used in a schemaless way. So an individual person may have `{name, age, height}` while another has `{name, age, favorite_color}`. Optionally, you may lock down classes so they cannot have extra properties.

The point is that you can mix schemaless, schema-mixed, and schema-full data design.

I have equated "label" with class for spider. It would be possible to have a property in a record called "label" if you wanted to, but there is no special significance for orient.

**Comment by dmill-bz** [comment]
ok great thanks for the info! Is it possible to have two classes with the same name? `Language extends E` and `Language extends V`?
Just so I can understand some edge cases that would work with some DBs and not others.

**Comment by electricjones** [comment]
I did not know the answer to that question, so I just tried it. No, they cannot.

Classes are also related to clusters. By default, a single class has and takes an entire single cluster. You can modify this and create classes to share clusters or classes that span multiple clusters. All of that is beyond spider though, I think.
