### ISSUE TITLE
Inserting multiple records via the QueryBuilder

### ISSUE THREAD

**Issue by electricjones** [spider/spider#42]
As of now, it is only possible to insert a single record per query in the query builder.

``` php
$query->into('target')->insert($data);
// or
$query->insert()->data($data)->into('target')->go();
```

It should be easy to insert multiple records at once.

``` php
$query->into('target')->insert([
   [ 'name' => 'michael']
   [ 'name' => 'jonothan']
]);
```

Something to keep in mind, though, is that some databases allow nested properties, like OrientDB which is also a document database. Therefore, the processor should check to see if the `$data` in the `Bag` is an array of arrays AND that the `$data` array contains only indexes (0, 1, 2, etc) and not key-value pairs.

**Comment by dmill-bz** [comment]
Yeah there's a lot of stuff to think about here given property cardinality and such. Both of these should be possible and be different:

``` php
[
   'name' => 'elizabeth',
   'name' => 'liz' // although this isn't valid PHP it's valid as far as data storage goes for some graph DBs.
]
```

and

``` php
[
   'name' => ['elizabeth', 'liz']
]
```

**Comment by electricjones** [comment]
The issue with the second one is in the Language Processor deciding if we want two records, or one record with two names (which is supported in Orient, at least).

**Comment by electricjones** [comment]
I would probably suggest restricting multiple inserts to:

``` php
[
     ['name' => 'elizabeth']
     ['name' => 'liz']
]
```

But we can add sugar to the QueryBuilder to make it more palatable. I just feel like a language processor would know exactly what to do with the above.

**Comment by dmill-bz** [comment]
Well in my two examples the first one was meant to be one record with two String names, and the second example was one record with one array name (containing two names). Both of these are possible.

There's a third case as well. That the record would have two "name"s that are both an array of several other items.
So it becomes quite complicated.

**Comment by dmill-bz** [comment]
here's what I'm trying to get to:

Case of multiple inserts (multiple vertices for example):

``` php
[
   ["name" => "something"],
   ["name" => "other"],
]
```

Case of the name property having a cardinality of `single`:

``` php
[
   ["name"=> "something"],
]
```

or even though the cardinality is `single` the value can be an array:

``` php
[
   ["name"=> ["something", "other"]],
]
```

Then the case of a cardinality of `multiple`

``` php
[
   [
      "name"=> "something",
      "name"=> "other"
   ],
]
```

or the same with arrays:

``` php
[
   [
      "name"=> ["something", "other"],
      "name"=> ["bla", "ni"]
   ],
]
```

Of course both of the above are invalid PHP so we will need to figure something out.

**Comment by electricjones** [comment]
Alright, now I follow. In honesty, most implementation of the cardinality single is about 3 lines of code inside a Language Processor. In this case, the `CommandBag` would simply hold `$data` which could be represented in any of the ways above. It is up to the processor to know whether they are creating a single or multiple records and act accordingly. If `$data[0]` is set, then we are creating multiple records.

So, from the user's POV:

``` php
$query->into('target')->insert([
     'name' => 'book',
     'role' => 'shephard'
]);
```

Would create a single record. While

``` php
$query->into('target')->insert([
     [
         'name' => 'book',
         'role' => 'shephard'
     ],
     [
          'name' => 'Kaylee',
          'role' => ['mechanic', 'engineer']
]);
```

Would create two records. In reality, the builder just passes the data as it is to the command bag and the processor sorts it out.

As far multiple carnality goes, it may be best to implement a simple DTO class like:

``` php
$query->into('target')->insert(
     [
          new MultipleProperties(
                'name', 'elizabeth', 'michael', ['caleb', 'jason']
           ),
          'age' => 25
    ],
     [
          new MultipleProperties(
                'name', 'simon', ['river', ['wash', 'zoe']]
           ),
          'age' => 30
    ]
]);
```

Which would be equivalent to two new vertices:

``` php
[
     'name' => 'elizabeth',
     'name' => 'michael',
     'name' => ['caleb', 'jason']
     'age' => 25
],
[
     'name' => 'simon'
     'name' => ['river', ['wash', 'zoe']],
     'age' => 30
]
```

Simple `func_get_args()` should allow for that syntax, and (again) it would be the processor's responsability to turn `$data` into a command that would produce the correct vertices. Of course, only in languages/databases that support it. Again, an exception may be the best way to handle those that don't (I know orient, gremlin, and neo do).

**Comment by electricjones** [comment]
As of this pr, spider supports the following cardinalities: single and multiple, but not set.

Single: (supported)
`{name: 'michael'}`

Multi: (supported, but up to the driver to implement)
`{name: ['michael', 'jason']}`

Set: (not supported)
`{name: 'michael', name: 'michael'}`

Currently, tinkerpop supports set, but according to the mailing list (http://mail-archives.apache.org/mod_mbox/incubator-tinkerpop-dev/201504.mbox/%3CJIRA.12818605.1428327870000.57919.1428696675143@Atlassian.JIRA%3E) this may be dropped down to only single and multi. Orient is looking into set cardinality, but I don't believe Neo supports it yet.

I suggest we stick to only single and multiple cardinality for now. If the need arises, we can add support for set cardinalityin the future. I'd rather someone open an enhancement issue for a use case. Or let driver's support it natively, maybe via an extension.

**Comment by dmill-bz** [comment]
The feedback from the TP mailing list was in favor of keeping `single`, `list` and `set` actually. The issue was also closed. With that said I completely agree on leaving this for when someone requires it. So lets stick to `single` and `list`.

**Comment by electricjones** [comment]
Great.

**Comment by electricjones** [comment]
Closing this with PR #44. We can discuss set cardinality again if it comes up.
