### ISSUE TITLE
Documenting Builder, best practice

### ISSUE THREAD

**Issue by dmill-bz** [spider/spider#48]
Hey, opening a discussion around this as it's going to be an important piece of the docs.

Here's how I feel about it:
- The docs should probably use a default graph (modern) and then provide examples of use for all the Builder methods (actual real case scenarios with results). Similar to how tinkerpop3 does it with their traversal documentation. This doesn't have to be in depth, just some basic examples.
- The code document blocks should have extensive input documentation that goes over every possible input scenario for each method (ie: property cardinality for insert, all where scenarios etc..). 

That way the documentation helps you get up and running and if you need nitty gritty specifics for each method you can get it directly from the API. 

On a side note, we have a lot of sugar methods and I feel this is a little confusing. Which should I use? `set()`? `get()`? `all()`? what's the difference between `one()` and `get()`?
Obviously I understand these differences but it's still a valid concern. Perhaps in this case only `all()` and `one()` should appear in the documentation and the others simply documented in the API?

**Comment by electricjones** [comment]
It has been on my todo list to revamp the docblocs before the release of 0.3. I'd like for the docs to be a basic, but complete guide.

I think the best thing to do with the sugars (especially all the retrieval methods) is to move them to the advanced page. We can link to it from the Builder (explore more...)

I do like the idea of using a real graph. Truthfully, I have the graph that is used in the documentation. I created it for fun at a talk I did. It's all based off the T.V. show firefly -- which is kinda an inside joke for my team. We name all our projects after Firefly elements.

I have always loved documentation that does little things like that to make the reading more interesting. Less dry. A subtle sense of humor. Then again, I'm probably a rare person who actually _reads_ documentation, not just google answers. My background is also in storytelling, so I'm partial. Actually, all of this (for me) is about creating storytelling and education tools.

So, all that said, I am open to the idea of putting this test graph out there, and definitely (either way) using a visual representation in the Builder portion. Let me sit on the idea of using modern graph. It's probably the right move, it just makes me sad. :cry:

PS: I love the gremlin story that runs around tinkerpop. Eventually, I'd love to co-opt the idea for spider and have a little mascot. But first, there should be working code.

**Comment by smolinari** [comment]
Docs on details, which have a bit more to them than just "dry" reading, are always the better choice. Especially when they help drive home overarching concepts at the same time. Docs should always also include, and possibly even start from, the overarching concepts. For instance, I am still a noob, when it comes to graphs. Like how do they serve a much better purpose, when it comes to relational data? Why and when should a graph even be considered? How will Spider and one of the supported databases help my project to this end? Then how do I get this needed data graph persistence job done? That is where the builder docs would come in, I would guess.

Scott

**Comment by electricjones** [comment]
It probably would be a good idea to include a "getting started with graphs" section and lay out different graphdb options.

**Comment by smolinari** [comment]
:+1: 

The technology of graph databases is relatively new and people need to understand the gains and benefits of them in order to see a reason to even look into them.

Scott

**Comment by dmill-bz** [comment]
Just wanted to point out that I think we should do this once we have a more or less final version of Builder (with traversals and all). That way we don't go back and forth in the docs as we add/remove builder features.

**Comment by electricjones** [comment]
Agreed. To be honest, I was thinking of a compromise. Once we have fixtures loaded from a file (which only requires the next step of a builder), then we can have a sample graph for the documentation that can be loaded at whim for users to play around with. Then, all the documentation uses that sample database, with elements of a story (similar to tinkerpops gremlin story).

**Comment by smolinari** [comment]
That would be totally cool! 

Scott

**Comment by electricjones** [comment]
For this release, I rewrote it for modern graph and added a graphic.

**Comment by electricjones** [comment]
Closing this. Just cleaning up.
