### ISSUE TITLE
Heads up about some repo changes

### ISSUE THREAD

**Issue by electricjones** [spider/spider#5]
I know there are a couple people following the development of this repo, so I wanted to mention some things I believe I'll change next week.
1. I am going to rename the repo chrismichaels84/spider (composer: michaels/spider), and drop the graph suffix.
2. I have built out an OrientDB driver in the develop branch, but will split it out to its own repo chrismichaels84/spider-orientdb.

The hope is that the naming convention will remain for drivers and framework integrations (vendor/spider-laravel, etc)

I am focusing on OrientDB for now because my current project is using OrientDB as a datastore with Laravel as the php framework. My hope is that this real-world use will help guide the api design and such. I am always grateful for any comments, especially about API and methodology.

Thanks.

**Comment by electricjones** [comment]
I have secured the spider organization and transferred Spider-Graph over. Sometime this week, I want to
- [x] Rename Spider-Graph to spider (spider/spider)
- [x] Extract the orientdb driver to spider/spider-orient-driver
- [x] Initiate real documentation at spider/docs
- [x] Change the PHP namespaces to be Spider\ instead of Michaels\Spider

I wanted to give some heads up, because I am not sure how it will affect forks. Let me know if you have any concerns or questions.

**Comment by electricjones** [comment]
I had a conversation with a couple colleagues who have done the same thing: split a core repo into its component parts and used composer to glue them all together again. They said it was a nightmare, especially if the core repo didn't have much functionality without the other components. Managing version, collaboration, and documentation all skyrocketed. They warned against extracting the drivers for now. Maybe later, if needed.

I think I agree. For now, lets keep the drivers as part of the core (spider/spider) and focus on the two we have going now. Once we get an api settled and some basic functionality, maybe we can reach out to a couple more (Neo4j, Titan) for drivers and CommandProcessors. I would also like a explore a SQL driver at some point.

We can keep a few core drivers inside the main repo. If someone wants to add more, its a simple `composer require`.

Agree?

**Comment by dmill-bz** [comment]
Yeah that sounds good. 

Also the gremlin driver covers Titan already as Titan uses gremlin-server.
