### ISSUE TITLE
Cypher processor

### ISSUE THREAD

**Issue by dmill-bz** [spider/spider#50]
Hey I've got questions in regards to this. I figured we could open an issue while I finish this dev.

I'm currently just going through the tests to make a failing Cypher processor test and I wanted to know about this query:

``` php
$query = 'SELECT field1, field2';
$query .= ' FROM target';
$query .= $this->getWhereSql();
$query .= ' GROUP BY groupField';
$query .= ' ORDER BY orderField DESC';
$query .= ' LIMIT 3';
```

The logic seems a little off in the sense that you are grouping by groupField but ordering by another field entirely (that would be lost in the grouping process). It's important to get the logic right here as cypher doesn't have a `GROUP BY` clause which means that I need to construct an equivalent.
Same with the selecting of fields that would be lost in the grouping process. We should change this around to be something more realistic. Maybe just drop the `GROUP BY` and place that in another test?

**Comment by electricjones** [comment]
You are right. I was just trying to create a complex query bag and wasn't really thinking about a practical scenario. I am fixing the BaseTest and Orient Test now. Should I push to develop or would you rather a pull request (don't want to screw with what you are working on now)

**Comment by dmill-bz** [comment]
The other issue is that there should be a clear separation of logic between label and type.

In both gremlin and cypher you choose the type of element you want and then the label within that type. 
ie: I want a `vertex` with label `target` and/or an `edge` with label `target`, or both. The query for these would be different. (whereas I feel it would be the same query in orient).

This means that the use of `from()` is ambiguous at best. There's no intuitive understanding of what it refers to and technically in graph DBs it doesn't have much meaning other than referring to a subset of the graph (which is what `where` is for). I understand that in orient they've made label/class analogous of RDBMS tables because it made the transition easier, but this is an incomplete abstraction and doesn't represent graph logic properly. 

At best I could see from() being used as an optional field to specify if we're looking to get `vertices` or `edges` (as opposed to the default `both`)

There could be several ways of going about it. Here are a few:

``` php
// using where. This could work for IDs as well (as we discussed ID cases in one of our previous exchanges)
$builder->select()->where(Builder::ELEMENT_LABEL, 'user'); // fetches user labelled elements (both V and E) 
$builder->select()->from(Builder::ELEMENT_VERTEX)->where(Builder::ELEMENT_LABEL, 'user'); // fetches user labelled vertices 
$builder->select()->from(Builder::ELEMENT_EDGE)->where(Builder::ELEMENT_LABEL, 'user'); // fetches user labelled edges

//some other random idea, this doesn't really help with the user scenario:
$builder->select()->from(':user'); // fetches user labelled elements (both V and E) 
$builder->select()->from('V:user'); // fetches user labelled vertices 
$builder->select()->from('E:user'); // fetches user labelled edges
```

I like the first better as it makes more sense. (no more need for specific methods to fetch IDs, or introducing new methods for LABELs). It has the downside of either being verbose or introducing reserved keywords (`_label` and `_id` probably)
Orient processor would have to do a bit more work to make up for the missing abstractions on the server level though but it shouldn't be that hard

**Comment by dmill-bz** [comment]
Ah thanks! develop is fine. I haven't committed anything yet, I can just stash it, pull the develop and apply again

**Comment by dmill-bz** [comment]
Thinking about my example maybe it could be:

``` php
class Builder {
   const E_ID
   const E_LABEL
   const E_V
   const E_E
}
```

Or something. It keeps the code clear when writing queries and is short enough not to be too verbose.

**Comment by electricjones** [comment]
This looks great. Orient is the odd duck and I don't mind it going through extra hoops. If you want to implement these in the Cypher processor, I can make orient match that.

For what it's worth, I like keeping from as sugar for those making the transition. Maybe:

``` php
$builder->select()->from($label, $type)->where(); // Where type would default to both vertex and edge
```

**Comment by electricjones** [comment]
At the base builder level, we can introduce:

``` php
// using where. This could work for IDs as well (as we discussed ID cases in one of our previous exchanges)
$builder->select()->where(Builder::ELEMENT_LABEL, 'user'); // fetches user labelled elements (both V and E) 
$builder->select()->from(Builder::ELEMENT_VERTEX)->where(Builder::ELEMENT_LABEL, 'user'); // fetches user labelled vertices 
$builder->select()->from(Builder::ELEMENT_EDGE)->where(Builder::ELEMENT_LABEL, 'user'); // fetches user labelled edges
```

**Comment by dmill-bz** [comment]
ok sounds good I'll add those changes. Once we're up and running on cypher and orientSQL we should probably make a new issue to discuss sugar aliases we want to add to Builder (for a birds eye view)

**Comment by electricjones** [comment]
Yes. If you can workout the base builder, don't worry about the from sugar in the Builder. I will take care of that.

**Comment by electricjones** [comment]
You know, we can drop group by entirely. I've never used it and its easy enough to filter results in a response object on the user side. If someone begs for it later, we can consider it an enhancement.

**Comment by dmill-bz** [comment]
I didn't include groupBy in the recent PR for cypher. Maybe we can reintroduce this later.

**Comment by electricjones** [comment]
I'm of the mind of: "build stuff for you and your friends, and then let others tell you how to improve it." If someone wants group by, they can open an issue. For now, we have bigger fish to fry.

**Comment by dmill-bz** [comment]
Agreed.
