### ISSUE TITLE
Builder and Query Responsibilities

### ISSUE THREAD

**Issue by electricjones** [spider/spider#53]
A recap of the conversation started in #22:

---

_@PommeVerte_ Aaaaaand while I'm at it. I've been thinking that we should provide a `TraversalBuilder` that extends `BaseBuilder` with a traversal syntax. I know we originally wanted to add sugar to Builder for this but thinking about it, it will be too complicated to do something clean (overlap and conflicts between what some methods would do). I have a couple of ideas here as well.

---

_@chrismichaels84_ Oh I didn't think about `Query`. `Builder` and `TraversalBuilder` would have been two leaves (it's not possible to have it function properly any other way as all the methods would function differently in populating the Bag) so maybe that would imply a different Query class as well.

I'd much rather add the basic traversal features to `BaseBuilder` so it can:
1. CRUD vertices and edges with labels and types (already implemented)
2. Manage relationships between vertices (`$builder->addEdge($from, $two, $label, $properties` or something)
3. Perform basic relationship queries (get all friends of user 3 who have been friends more than 2 years, or get all posts tagged as new and important, etc.)
4. Perform powerful, if verbose queries, sub queries, and traversals.
   ________________
   _@PommeVerte_ I think a lot of what you mention would probably be better on the `Model` layer. It's an abstraction on the logic (query construction) and not really query sugar. 

Also all methods would conflict.

``` php
$builder->out()->out()->where().
```

The `where` here would have to function completely differently to the current where that just adds stuff to the bag since this where would need to apply to some sub query. Actually a lot would have to be happening in the above. Anywho I don't see a `where()` or many other methods working for both scenarios.
Also what happens if you use `out()` in a declarative scenario? Sounds like a headache waiting to happen. I don't think there's much harm in providing two builders, two queries is a bit more of an issue though.

---

_@chrismichaels84_ I don't mind two builders. Its the two queries that rub me the wrong way. It complicates things for the user having to choose between or carry two different objects around in their code. This may be simplified in the top level api like

``` php
$spider->traverse($start)->out()->out()->with();
$spider->query()->select()->from();
```

But that still seems unwieldy.

Having two builders also makes it difficult for a higher abstraction (model) to know which builder to use without being explicitly told. At the end of the day (top-level), the user shouldn't have to make that choice. They should declare what they want from a `model` or `spider` and it happens.

If we use subselects (as orient sql does), then most of the above is possible (with the exception, maybe, of number 4. I'd have to ask around).

---

**Comment by electricjones** [comment]
This comment will be edited as we come to some decisions about responsibilities:
- `BaseBuilder`
  - Manage CRUD operations for types and labels
  - Where constraints, targets, and ordering
  - Produces a `Commands\Bag`
- `Builder`: 
  - Sugar for the `BaseBuilder`
  - Process the `Comands\Bag` into a `Command` using an instance of `ProcessorInterface`
- `Query`: 
  - Add explicit dispatching methods (all(), one(), first(), etc)
  - Wraps some `Builder` methods for dispatching (drop(), insert(), etc)

**Comment by electricjones** [comment]
So, it occurred to me that we may be using terminology a little differently. I wanted to clear up my thoughts on a few things concerning relationships, traversals, and queries.

It may be best to speak of three distinct (though related) things:
1. _CRUD operations_ are what are completed now. Create, retrieve, update, and drop vertices. Allows for complex queries, but only on vertices.
2. _Relationship Management_ adds the ability to connect two (or more) vertices by edges. Also allows for querying based on simple relationships (get all users who have an outgoing relationship 'follows') . Not sure to what extend this piece does complex querying. Its primary responsibility is to CRUD edges.
3. _Traversals_ are for complex querying, and querying _only_. Finding paths, distances, depths, etc.

Some general thoughts about the above:
- That said, I think a sub-object for traversals may be a good idea. So that `$query->traverse()` allows for a different api for complex traversals.
- Relationship management should be handled by `BaseBuilder` with methods like `createEdge()`, `updateEdge()`, and `dropEdge()`.
- Also, in `BaseBuilder` add logic to basic where constraints to do simple querying based on edges.

I am going to simplify the where mechanism in the base builder, moving a lot of the logic to `Builder`. So, `BaseBuilder` will only accept an array of arrays, each constraint being fully detailed, using constants and not aliases. `where([['username', Bag::EQUALS, $value, Bag::CONJUCTION]]);`

Thoughts?

**Comment by dmill-bz** [comment]
Given neural scenarios I think it's important that traversals allow for mutations of the graph. Hence traversals shouldn't be for querying only. (By querying I understand reading). Of course setting this up involves that BaseBuilder has the ability to do so as well, though we may decide not to document this entirely as some aspects could make for overly complex `Builder` queries. Anything complex should be done through a `TraversalBuilder`.

**Comment by electricjones** [comment]
Agreed.

So we are looking at something like this for `BaseBuilder`. PS: I use abbreviated constants.

``` php
$properties = [
    'from' => $from,
    'to' => $to,
    'direction' => $direction,
    LABEL => 'is_following'
];

BaseBuilder::insert($properties)->type('EDGE');
BaseBuilder::delete()->where([TYPE, EQUALS, EDGE, AND]);
BaseBuilder::update($newData)->where([TYPE, EQUALS, EDGE, AND])->where([]); // other constraints
```

This way we don't really add much to the Base Builder, but we give it the ability to manage edges. The work falls to the processors, as it should. We can then add sugars to `Builder` like 'createEdge()`, etc.

As far as querying (reading) goes for the `BaseBuilder` what should it be capable of?

My thoughts is that the `BaseBuilder` should mimic what most people would use MySQL for: getting records and those connected to them (like post and comments).
1. Limit traversals to a dept of 1, that vetex->edge->vertex
2. Get connected vertices based on condition. Returns posts and comments

``` php
$baseBuilder->select()->from()->where()->with(['outE', 'has_comment');
// Not sure what format this would return. I would think this to be the closest to join.
```
1. Get vertices based on whether a relationship exists

``` php
$baseBuilder->select()->from()->where([
   ['outE', EQUALS, 'label', AND],
   ['outE.date', GREATER_THAN, '4', AND]
]);
```

The `TraversalBuilder`, then would follow its own logic for more complex operations. May be worth patterning it after cypher or gremlin.

**Comment by smolinari** [comment]
Because I couldn't imagine what "neural scenarios" could be in a PHP program or why a traversal could or should allow for mutations, I went looking for some possible explanations and found this article among a couple others. 

http://markorodriguez.com/2011/07/14/graphs-brains-and-gremlin/ 

It is a bit old. but wow. Neural algorithms with PHP? Who would have thought that? LOL!

Scott

**Comment by electricjones** [comment]
Yeah, a big part of this project (for me) is to help in lending some legitimacy to php, especially as php 7 approaches. The community and resources for php is incredible, and I don't see why it couldn't be used for (at least) moderate data science, especially when focused around a web app or RESTful API.

**Comment by smolinari** [comment]
Although I can understand your motivation fully and agree with it, you can only make PHP more legitimate. I mean, it is already quite legitimate. It powers 80% of the Internet. :smile: 

Scott

**Comment by dmill-bz** [comment]
I'm going to leave the Edge talk for issue #81 and instead concentrate on the relationship aspect of things.

@chrismichaels84 I don't think there should be any depth limit. The suggestion I'll make in this post for handling relationships should work for any depth. 

Before going any further I wanted to place two distinct user cases out there so we have something to work with. I consider depth (d) 0 to be the initial starting set:
1. We want `d = 0` elements but we want to make sure that some conditions (say `name = "obama"`) are true for `d(friends) = 2`.
2. We want `d(friends) = 2` elements with `name = "obama"`

Immediately the question of whether or not to use `where()` for both scenarios comes into play. Is it even semantically correct to consider this?

Here's what I mean (using non definitive pseudo params for where):

## 1

``` php
(new Builder())->select()
               ->where(
                  ["name" => "michael"],
                  [
                     'out'=>"friend"
                     'where'=>[
                        'out' => "friend", 
                        'where' => ['name' => "obama"]
                     ]
                  ]
               );
```

This flows naturally. We want to select `d = 0` where obama is two hops away.

## 2

``` php
(new Builder())->select('b')
               ->where(
                  ["name" => "michael"],
                  [
                     'out'=>"friend"
                     'where'=>[
                        'out' => "friend", 
                        'where' => ['name' => "obama"], 
                        'as'=>"b"
                     ]
                  ]
               );
```

The semantics here are a little odd. We aren't really selecting `b` where anything.. if that even makes any sense. 
Of course the above is readable and quite straightforward but do you guys not feel like it's slightly odd?

---

Anyways, with the above in mind here's what I would suggest:

`Processor` should have methods that **return** data rather than directly append them. (you can check the `CypherProcessor` to see `buildX()` vs `appendX()`). 
With this `BaseBuilder::$where` could contain both `array` lines that describe a property constraint, and `Bag` lines that describe a relationship.

`Processor::buildX()` could then simply handle the `array` scenario like it currently does (no change required). When it runs into a `Bag` however it spawns a new `Processor` instance with that bag and runs `(new)Processor::buildX()` on that. It can then append the return string from that call wherever it needs to be.

It might be interesting to make a `LinkBag extends Bag` to add some link information to the Bag. And same with `BaseBuilder` there should probably be a way of constructing a "link builder" of some sorts.

The verbose `BaseBuilder` way of writing the relationship could be something along the lines of:

``` php
(new BaseBuilder())->select()
               ->where([
                  (new BaseBuilder())->link(Bag::LINK_OUTE)->select()->where([LABEL => "friend"])
               ]);
```

Or some variation.

What do you think? Was that clear enough?

**Comment by electricjones** [comment]
Yeah, I don't like **2** at all. **1** is very readable to me and would be relatively easy for a newcomer to graph databases to understand. We also already use `select()` to define projections, and I'd like to keep it that way. It's so standard in the orm world.

That does, however, seem a little imperative to me. What if you do not know the depth? What if you want a depth of 3 the first time, but a depth of 7 the next time.

Actually, as I type, I realize that scenario would be better in a `TraversalBuilder`, which is a separate discussion. I am fine with having to know your depth and write explicit queries for the standard `Builders`.

For reference, that is how orient sql handled the problem. If you know the depth, you can simply write a SELECT statement, but if the depth is unknown, you write a TRAVERSE statement.

In our case, I like the `TraversalBuilder` being a sub-object inside a `Builder`. `$builder->traverse()-etc()`. A discussion for later.

I love the idea of `Processors` returning data. It's very straight forward. That would also help us in our discussion of #81 in the way that we nest queries.

**Comment by dmill-bz** [comment]
We could eventually envision a `depth()` method to work around some of these things. But that's probably something we can look into later. 

So we will need to think about **2** and come up with some ideas. 

And I agree about the `TraversalBuilder`.

What's your stance on `link()` can you think of anything more fluent?

**Comment by electricjones** [comment]
What about something like:

``` php
(new Builder())->select()
               ->where(
                  ["name" => "michael"],
                  [
                     'out'=>"friend"
                     'where'=>[
                        'out' => "friend", 
                        'where' => ['name' => "obama"], 
                        'as'=>"b"
                     ]
                  ]
               )->return('b');
```

Assuming `return` is a valid method, and i'm pretty sure it isn't in PHP.

Also, this is all in `Builder` with simplified `where` statements. If using `BaseBuilder`, then we would have to use constants for operators and conjunctions. Just wanted to note that.

**Comment by electricjones** [comment]
I'm on board with a `LinkBag`, so long as its abstracted away further up the chain. Preferably the `Builder` layer, but definitely the `Model` layer.

**Comment by dmill-bz** [comment]
Well technically `b` is a projection so it would make more sense to have it in `select()` provided the current implementation. Maybe we can change that for a return method but it's kind of weird not calling it `return()` (which we can get to work via `__call()` though it feels like a roundabout way of doing things) 

I was wondering if something like this wouldn't be an option as well:

``` php
(new Builder())->select()
               ->where(["name" => "michael"])
               ->fetch(
                  [
                     'out'=>"friend"
                     'where'=>[
                        'out' => "friend", 
                        'where' => ['name' => "obama"],
                     ]
                  ]
               );
```

`fetch()` vs `follow()` vs etc.

**Comment by dmill-bz** [comment]
for posterity:

``` php
class A {
    public function __call($method, $args){
        if($method == "return")
        {
            return call_user_func_array([$this,"internalReturn"], $args);
        }
    }

    public function internalReturn($a){
        return $a;
    }
}

$a = new A();
echo $a->return('lala'); // lala
```

**Comment by electricjones** [comment]
Wow, I like `fetch` so much better than using return. Let's stick with that and we don't have to workaround `return` or worry about storing variable names, which may complicate things once we create variables for Builder instances.

And, while these are technically projections, I would like to keep `select()` as compliant with SQL as possible.

``` php
(new Builder())->select('name', 'country')->from('person')
               ->where(["name" => "michael"])
               ->fetch(
                  [
                     'out'=>"friend"
                     'where'=>[
                        'out' => "friend", 
                        'where' => ['name' => "obama"],
                     ]
                  ]
               );
```

Would return a `Collection` with only the name, country, and meta of the the `friends.friends` of michael whose name is `obama` (It would be cool to be friends of a friend of obama, btw)

**Comment by dmill-bz** [comment]
I think `as()` is going to be required regardless of what we do. Look at it as a MYSQL `table AS alias`.
For instance : 

``` php
(new Builder())->select('a.name', 'b.name')
               ->where(["name" => "michael"])
               ->fetch(
                  [
                     'out'=>"friend",
                     'as' => 'a',
                     'fetch'=>[
                        'out' => "friend", 
                        'where' => ['name' => "obama"],
                        'as' => 'b',
                     ]
                  ]
               );
```

In that case `fetch` becomes a bit of a third wheel to `where`.

It's going to be a requirement for `path` and `tree` anyways. If the user doesn't manually set it the processor will have to do it (`CypherProcessor` already does this partially).

The more I look at it the more I'm tempted to go back to : 

``` php
(new Builder())->select('b')
               ->where(
                  ["name" => "michael"],
                  [
                     'out'=>"friend"
                     'where'=>[
                        'out' => "friend", 
                        'where' => ['name' => "obama"], 
                        'as'=>"b"
                     ]
                  ]
               );
```

Perhaps making it:

``` php
(new Builder())->select('b.*')
```

would feel closer to home.

**Comment by dmill-bz** [comment]
or `return()` could also work.. decisions, decisions.

**Comment by electricjones** [comment]
I vote for `select('b.*')`. It feels consistent with dot-notation, and would allow you to modify that any way you like.

Let's settle with

``` php
(new Builder())->select('b.*')
               ->where(
                  ["name" => "michael"],
                  [
                     'out'=>"friend"
                     'where'=>[
                        'out' => "friend", 
                        'where' => ['name' => "obama"], 
                        'as'=>"b"
                     ]
                  ]
               );
```
