### ISSUE TITLE
Improve Test Coverage

### ISSUE THREAD

**Issue by electricjones** [spider/spider#54]
Right now, our test coverage is suffering from a lot of little things and a few big things. I'd like to tackle a few before we get too far ahead of ourselves.

**Comment by electricjones** [comment]
PR #55 cleans up the test coverage a lot, but there are some bigger concerns that I just didn't want to deal with right now. Would love some outside help. These should be easy:
- [x] Remove `Graph\ID` entirely. It's only referenced in a test or two to normalize the way record IDs are handled by the different database. There has to be a more elegant way to do that.
- [x] Improve testing around the `formatAsX` methods in the Drivers. Granted, this will come once we have settled on formats
- [x] test `runRead` and `runWrite` commands

**Comment by dmill-bz** [comment]
I've partially removed `Graph\ID` already in my upcoming PR. I'll elaborate once I push everything.

**Comment by dmill-bz** [comment]
PR #56 covers the `Graph\ID` case.

Thought of something but the `runRead` makes little sense since you want to get something back from the DB when you're reading. Maybe we can remove this altogether, and instead of `runWrite` we should just call it `run` (the write nature being implied).

**Comment by electricjones** [comment]
Totally agree. runRead serves no purpose. I like run. I'll take a look through the rest of this tomorrow.

**Comment by electricjones** [comment]
I'm closing this. It'll come as we move forward.
