### ISSUE TITLE
Travis, Code Coverage, and Analysis

### ISSUE THREAD

**Issue by electricjones** [spider/spider#57]
It's been a long road of blood sweat and tears (well, maybe a little carpel tunnel), but 0.3 is on the horizon. All we really have is some cleanup to make sure everything passes and is consistent across the board and to make sure documentation is up to snuff. See #21.

On that note, it's probably important to get TravisCI, code coverage, and analysis up and running. When I stumble on a package (after making sure it fits my needs) these are the first things I look for. It at least tells me the developers take things seriously. Also, if the main goal of 0.3 and even 0.4 is to get others on board, this building is important.

I had a TravisCI setup at one point, but I think it was detatched when I moved it into spider/spider. Coveralls was setup through TravisCI and I don't know if SensioLabs was ever working in the first place.

It may be best to reattach these things under a spider organization username instead of an individual. It may also be worth looking into code climate or something similar.

Refer to #35.

**Comment by electricjones** [comment]
I've setup Travis and executed the first build, which actually failed for some of the jobs but not others. You can see at https://travis-ci.org/spider/spider/branches. 

Working on Coveralls and Insights now.

**Comment by electricjones** [comment]
Well, I've got Travis and Insight setup.

Travis is erroring when it tries to extract gremlin-server.

Insight is giving us a silver medal for really stupid reasons. I'll take a whack at this tomorrow.

Coveralls is still not recognizing the organization unless I disable any restrictions on third-party applications. I don't like doing that.

All that said, it has merged, docs have build, api docs have build, and all seems well. Let's let it sit for a bit, maybe figure out travis, coveralls, and insight. In either case, I'm comfortable releasing officially Sunday.

Should this be a pre-release? I would think so.

**Comment by smolinari** [comment]
I would say, anything before 1.0.0 GA is a pre-release.:D ;)

Scott

**Comment by dmill-bz** [comment]
Travis errors we somehow unrelated. I reran the tests last night and they passed. maybe their servers were overloaded. Let me know what comes out of coveralls as I'm probably running into the same issues with scrutinizer.

**Comment by dmill-bz** [comment]
Maybe you can create an organization in scrutinizer since you are the repo owner it probably wouldn't complain. And you can add me to the organization (I'll set things up from there)

https://scrutinizer-ci.com

**Comment by electricjones** [comment]
I've created the organization, but I need your email to add you. If you don't want it public, you can email me at spiderogm@gmail.com.

**Comment by electricjones** [comment]
Alright, I got your email from JIRA and setup an organization, associated spider/spider with it, and added you as an admin. You should be able to configure it if there is anything left. Thanks.

**Comment by dmill-bz** [comment]
Thanks!! I understood what was odd about the rights. You might need to add spider/spider to the repos of the admin group. Also could you add "scrutinizer-auto-fixer" user to the committers group please? I don't seem to have rights to this group. 

Thanks!

**Comment by electricjones** [comment]
Okay, I think I've got everything setup except the code coverage.

**Comment by electricjones** [comment]
The good folks over at coveralls have reset everything, we're synced up and at 92% test coverage. I'm closing this ticket.
