### ISSUE TITLE
Neo4j fails a few tests, but only sometimes

### ISSUE THREAD

**Issue by electricjones** [spider/spider#63]
I've noticed that if I run phpunit several times in a row about 1 in 5 run throughs will have a failed test or two. It seems to be related to the basic querying. Usually the tests that fail are QueryBuilderTest::testBasicSelect or when executing a read command in the driver.

I think what's happening is that, occasionally, neo4j inserts records in a different order. So, when retrieving all records and checking for the first one, it may fail. I don't think its a problem with the library itself, but the tests may need reworked.

**Comment by dmill-bz** [comment]
This can probably be solved by adding ordering to our test queries to ensure correct output order.

**Comment by electricjones** [comment]
PR #72 takes care of this
