### ISSUE TITLE
Roadmap to v0.4

### ISSUE THREAD

**Issue by electricjones** [spider/spider#64]
Along with the milestone, this is a good place to keep track of our goals for the next release.
- [ ] Full Query Builder with
  - [ ] Traversals
  - [ ] Edge Management
- [ ] Top level Spider API
- [ ] `Gremlin\CommandProcessor`.

**Comment by dmill-bz** [comment]
The next two steps should be removing read/write and allowing for multiple CRUD operations in one query. After that we can work on relationships

**Comment by electricjones** [comment]
I've got read/write removed. Just squashing one last bug before a PR.

And, at least for orient, multiple opperations shouldn't be that difficult with the new Batch workflow. The trick will be deciding the api and how to use variables in those operations.

```
LET t1 = CREATE VERTEX person CONTENT {}
LET t2 = CREATE VERTEX person CONTENT {}
LET t3 = CREATE EDGE is_following FROM $t1 OUT $t2 CONTENT {}
```

Would you mind starting an issue to discuss this?

**Comment by dmill-bz** [comment]
Will do as soon as I have a second :)

**Comment by smolinari** [comment]
@chrismichaels84 @PommeVerte  - Things got pretty quiet around here. I hope all is well with you two? :smile: 

Scott

**Comment by dmill-bz** [comment]
Hey, yeah all is good on my end. I just have some projects to deal with in the upcoming weeks so although I'll be keeping an eye out here and participating, it'll be hard for me to submit any major PRs.

**Comment by electricjones** [comment]
I'm in the same boat for right now. Real projects (ones people pay me for) keep bogging me down :(. I should have a simple PR this weekend though.

@smolinari if you want to get involved, your last PR was good. I'm sure there are somethings that would be good fits for you.

**Comment by smolinari** [comment]
Give me some tips on what you think I could attack. I'd love to do more. I am just not very self-confident in my skills.

Scott

**Comment by electricjones** [comment]
Well, let me look through the code and todos and roadmap for some smaller items, but if you wanted to work toward something else, a few things come to mind. All of these would require work from each of us, but you could take some of the lead.

The first thing that comes to mind which might be fun are some framework integrations. If you use something like Laravel or Yii, it will be important to have ServiceProviders or bridges or whatever else to make integration easier.

Or, something else I've been thinking of, is a sample application of some kind. Pick an easy framework and a fun graph (like GratefulDeadConcerts or something from Star Trek) and create a simple application that uses Spider as a component.

There are also potential drivers for other graph databases or even non-graph databases. I'd love to see a MySql and Mongo driver and each of those could just wrap existing libraries.

Also issues #31, #24, and #23 need some groundwork laid and some research. Again, open an issue and we could all discuss it and choose which method to use. None of those issues should be complicated code-wise, once we settle on the directions.

If your more design-minded, a github pages site would be nice to start getting the word out there. Or  an "introductions to graphs" section of the documentation.

The last one that pops into mind is some work on the Fixtures, and an extension that allows users to load graphs. But that should probably wait for the full query builder.

If any of these jump out, just holler and we can all move forward. If not and you'd like something simpler, let me look through the code. Lots of refactoring could be done. I also would mind help over at http://github.com/chrismichaels84/data-manager, which is used by this library.
