### ISSUE TITLE
one() and first()

### ISSUE THREAD

**Issue by smolinari** [spider/spider#65]
This is getting nitpicky. I know. I was reading the docs to learn some more about Spider and something hit me about `one()` and `first()`. Actually, when I first saw `first()`, it seemed strange to me. It seemed like it should be a verb, like `getFirst()`. 

```
$person = $query
   ->select()
   ->from('person')
   ->where('name', 'vadas')
   ->getFirst();
```

Or maybe this could work?

```
$person = $query
   ->select()
   ->one()
   ->from('person')
   ->where('name', 'vadas');
```

Scott

**Comment by dmill-bz** [comment]
This is a good point. I'm used to the `one()` `all()` `scalar()` etc. because they've been present in a few libraries I use but maybe a `getX()` syntax would make more sense.

**Comment by smolinari** [comment]
Yeah, it is getting really nitpicky (if that were the only kind of problem to have, it would be great). So, not important at all. Just thought I'd mention it from my own humble usability perspective. 

Scott

**Comment by electricjones** [comment]
I can get on board with this, so song as its consistent:

getOne() - alias of getFirst(). I don't know if we need both, honestly.
getFirst()
getAll()
getScalar()
getPath()
getTree()
getSet()
get() -- alias of getAll()
dispatch() remains the same.

I don't mind `$select()->one()->where()->get();`, but all one would do is set limits

**Comment by smolinari** [comment]
I would say, if you have `getFirst()`, you don't need the `$select()->one()->where->get();`. It would then  simply be `$select->where()->getFirst;` (or `getOne();`)

As for both `getFirst()` and `getOne()` being needed, I'd vote for no, if they both do the same exact thing. If `getOne()` would do something different, like get any random result, but only one, then yes, keep it. 

What about `go()`? Is it an alias for `dispatch()` or vice versa? If they do both the same thing, get rid of one. I'd vote for getting rid of `dispatch()`. `go()` is simply more positive sounding and shorter. ;-)

Scott

**Comment by electricjones** [comment]
I don't have a problem with aliases because I like fluency. And as long as its documented, it works. `go()` and `dispatch()` are almost aliases. The only difference is the `dispatch()` has an optional argument. You can pass a `Command` straight through, if you like.

Honestly, `dispatch()` is more of an internal method, even though it is public for those who like that explicitness. That is fairly common in the orm libraries I've used.

`getOne()` and `getFirst()`, however, don't add anything to the fluency, in my opinion.

**Comment by smolinari** [comment]
hehehe...:smile: You're up against the master of hair splitting. LOL! 

From my perspective `dispatch()` is less fluent than `go()` and having the two methods, which do the same thing, doesn't add to fluency at all. The definition of fluency is 

> a speech language pathology term that means the smoothness or flow with which sounds, syllables, words and phrases are joined together when speaking quickly. 

and from a programming perspective a fluent interface is:

> an implementation of an object oriented API that aims to provide more readable code. A fluent interface is normally implemented by using method cascading (concretely method chaining) to relay the instruction context of a subsequent call (but a fluent interface entails more than just method chaining [1]). Generally, the context is:
> - defined through the return value of a called method
> - self-referential, where the new context is equivalent to the last context
> - terminated through the return of a void context.

Nowhere is there a mention of aliasing method names and it adding to the fluency of an API.

To me, having aliases only adds complexity and a chance for confusion for the client dev. "Huh, why do I have one() and first()? Do they do the same thing or is there a difference?" (the reason why I started this thread) In other words, there needs to be a clear reason for an alias to be there, otherwise it is superfluous and unnecessary and confusing. Making one() (or first()) a verb, on the other hand, does add to the fluency, as they are action methods to carry out a task and should "say that" in the name. It does an action, so the name should reflect that. 

And I also feel just because ORMs do something doesn't really mean it is automatically correct. I'd even bet any aliases came from the history of the development and not because of a straight-up decision, like, "Let's make a function that does the same exact thing as this other function, just so we have a different name for it! That should make our ORM more fluent." 

Nope. It was more like (and this is only an example), "Hmm....we started with dispatch(), but go() is so much more fluent. Let's add go() as an alias for dispatch(). We'll need to deprecate dispatch() at some point, but not to break BC, we'll keep it for a while." And maybe they forgot to deprecate it?

Please stick to the rule: one well thought out name per method. It helps keep things neat and tidy and it helps people be more fluent with the API, like me. 

Even Wikipedia agrees with me. 

> In computing, aliasing describes a situation in which a data location in memory can be accessed through different symbolic names in the program. Thus, modifying the data through one name implicitly modifies the values associated with all aliased names, which may not be expected by the programmer. As a result, **_aliasing makes it particularly difficult to understand, analyze and optimize programs**_.

:smile: 

Scott

**Comment by dmill-bz** [comment]
I agree. We should probably decide on one method name for each functionality. With that said, in the case of dispatch I'd be tempted to make it `protected` anyways so it shouldn't matter.

**Comment by electricjones** [comment]
Very detailed answer, and I appreciate that.

Everything does have a clear functionality, and I don't believe the aliases add to complexity. If anything it gives options. I may be alone here, but I like my code to be readable and speak in sentences. I like having the options of different aliases, so I can make my code more fluent.

That said, at this early stage, we can knock out the aliases.

BTW dispatch and go are not really aliases. `Dispatch` allows you to send a command through the query builder. I would vote that we make dispatch protected and (after I refactor Orient to not need read/write command distinction), reintroduce `command()` which will allow users to pass native queries through.

So, we would end up with:

| Method | Response |
| --- | --- |
| go() | returns `Response` |
| getAll() | returns Set |
| getFirst() | returns `Collection` |
| getPath() | returns Path |
| getScalar() | returns Scalar |
| getTree() | returns Tree |
| command() | returns `Response` |

**Comment by dmill-bz** [comment]
I'm torn between `getOne()` and `getFirst()`. The later implies your query returns a set when that is not necessarily true. I think `getOne()` is more versatile. If you're expecting a single response entry then it speaks for itself. If you only want the first element of a set `getOne()` would also function as expected.

**Comment by smolinari** [comment]
And since command isn't a verb, doCommand()? <- It is a question. _Scott ducks_  :smile: 

Scott

**Comment by electricjones** [comment]
maybe `dispatchCommand()`?

Or we could use dispatch here: `dispatch($command)`, keeping dispatch public or renaming the protected method that fires the command away `execute()`. Or vice versa.

I'm down with `getOne()`

**Comment by electricjones** [comment]
Okay, so let's settle with this for now:

| Method | Response |
| --- | --- |
| go() | returns `Response` |
| getAll() | returns Set |
| getOne() | returns `Collection` |
| getPath() | returns Path |
| getScalar() | returns Scalar |
| getTree() | returns Tree |
| execute($command) | returns `Response` |

`dispatch()` becomes protected.

@smolinari If you are up for getting involved, would you like to take a whack at this? It should be fairly simple for you to fork the repo and issue a PR against the `develop` branch. Everything is in `src/Commands/Query.php` and the tests are `tests/Integration/QueryBuilder/BaseTestSuite.php`. The logic of the methods should remain unchanged, just remove the aliases and conform them to the table.

If not, I'll take a stab at it when I get back in town :smile:

**Comment by smolinari** [comment]
I'd love to, as that sound like a relatively small challenge I can get done, without messing things up and it would also get me into more of the code, which I'd also love to do. 

However, I am sort of confused about which branch to use, develop or master?  It seems like develop is quite a few commits behind master, so my first inclination is to take master. But, I also know, normally master shouldn't be messed with, but rather branches of develop should be made to create PRs, if Spider is using Gitflow, which seems the case...sort of. 

One other question I have. Where are the docs located? I would imagine, if I make the changes, I'd need to also update the docs accordingly?

Scott

**Comment by electricjones** [comment]
`develop` is up-to-date and (now) past `master`. Work off of and pr against `develop` please. We should only merge into master from `develop` and maybe a security branch, if we decide to.

`Master` should always be even with the current release (from now on).

The docs are in the same repo. `/docs/command-builder.md`. Thanks a lot.

**Comment by smolinari** [comment]
Ok. I forgot about getting the upstream repo. I think I am good to go. So, I'll work on the changes in a branch from develop and request a PR from there, once I am finished. 

Scott

**Comment by smolinari** [comment]
I thought this might be of interest to you Chris. :wink: And honestly, I ran into the article through a totally different topic, which was immutable objects. 

http://ocramius.github.io/blog/fluent-interfaces-are-evil/

Scott

**Comment by smolinari** [comment]
Ok. PR is up. https://github.com/spider/spider/pull/71

The methods now should be like this. 

| Method | Response |
| --- | --- |
| go() | returns Response |
| getAll() | returns Set |
| getOne() | returns Collection |
| getPath() | returns Path |
| getScalar() | returns Scalar |
| getTree() | returns Tree |
| getSet() | returns a Set |
| execute($command) | returns Response |

Scott

**Comment by electricjones** [comment]
Meged #71
