### ISSUE TITLE
Cleaning up branches after release

### ISSUE THREAD

**Issue by electricjones** [spider/spider#66]
So, just so we're all on the same page, I like to keep my branches as trimmed as possible. So, after a release, I usually delete all the branches I can (including the `develop`), rebranch a new develop from master, and get going.

There are wip branches that I need, but before I deleted them, I wanted to check.

If all is clear, I propose we delete everything except master, open a new `develop` for 0.4 work, and then whatever feature branches we need off of that one.

I also like to have separate branches for security releases (_._.x) off the `master` branch. These should be relatively small, especially now. Maybe for 0.3.1 fix the ordering in neo tests per #63 and go through some of the code-quality stuff from #46. Then, after those are merged back to master, merge master back into develop and rebase/merge the feature branches appropriately. That way we don't get stuck waiting on a point release for a bug in the current release.

Thoughts?
Tomorrow is y last day on this side of the world for a week, but I can clean the branches before I leave. If you wanna start tackling some of the traversals and edge management. I'll push my mostly ready wip on the top-level api, just so you know where everything is heading.

Thanks for all your help!

**Comment by electricjones** [comment]
Or we can just take a week to do all the other stuff that's piling up, I'm sure, lol.

**Comment by dmill-bz** [comment]
I'm ok with that so long as removing the develop doesn't break local branches of people who've pulled the dev and we working on it in between releases. If it does then we should definitely chose to merge the master back into the dev instead (if there's some diverging)

**Comment by electricjones** [comment]
We can keep the development branch alive and just keep merge `master` changes back in. I'm more comfortable with that.

**Comment by electricjones** [comment]
Okay, I've cleaned up the branches, merged our `master` changes back into `develop` so its ready for 0.4 work, and created a `0.3.1` branch for the few things we may want to release before 0.4. (like neo-test ordering, and some orientdb refactoring).

I've also pushed `spider-api-exceptions` which is a feature branch of `develop` for 0.4. Details at #22.

And, with that gentlemen, I'm off for the week! I may check in on the issues while I'm away, but won't have my IDE or tools.

**Comment by electricjones** [comment]
We can close this anytime.

**Comment by dmill-bz** [comment]
ok I just pushed some changes to develop (tests more than changes). Do those then get merged down into `0.3.1`? What's the workflow like with all these branches? (should we assume we never merge directly to master from now on?)

**Comment by dmill-bz** [comment]
Also it seems like coveralls doesn't auto update on push and stuff maybe we should look into that.

**Comment by electricjones** [comment]
Well, the workflow I was envisioning was that work on new features go into develop, and we only use 0.3.1 for security things that need to be released before we actually release 0.4.0 (like a bug that fails on some systems or fixing the neo test). In that case, we would push those changes to 0.3.1, merge 0.3.1 into master and then master back into develop. From develop into whatever feature branches.

We shouldn't push directly to master and we should have a buffer between master and volatile branches. So, to me, `develop` is stable code for the next major release. And only `develop` or the next security, in this case `0.3.1` ever go into `master`.

I'm not married to this workflow, if you would like to propose something else. Honestly, at this point it doesn't matter terribly much as we probably don't even need 0.3.1, but I was thinking longer-term, when me may actually be releasing security patches.

**Comment by electricjones** [comment]
To be honest, I've never lead an open-source project with other contributors, so I'm open to learning more efficient workflows. That is the workflow we use on my team at Phoenix Labs.

**Comment by smolinari** [comment]
It seems you are pushing for Gitflow. 

http://nvie.com/posts/a-successful-git-branching-model/
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

Scott

**Comment by electricjones** [comment]
Adding this to contributing documentation for next release.
