### ISSUE TITLE
Query Builder Architecture and API

### ISSUE THREAD

**Issue by electricjones** [spider/spider#7]
I have begun working on the query builder aspect, now that the drivers are more/less set in place. I'd love feedback on structure and API.
## Architecture

My thought is to create a base query builder that contains no grammar for Spider, and then each driver provides a set of classes to be used as the grammar.

`Spider\Queries\QueryBuilder` is the master object that contains a `Connection` with the current driver as well as a vendor specific `QueryProccessor` which builds the actual query and returns a in instance of `QueryInterface` which the `QueryBuilder` sends through its connection and driver, returning the SpiderResponse (Record, Graph, or array).

**`QueryBuilder`**: Contains a connection and a query processor. Any query building methods (`->where()`, `->select()`, `->traverse()`) are passed via magic methods to the processor. The action methods (like `get()` or `first()`) get a `Query` from the processor and pass it to the connection.

**`Spider\Queries\QueryProcessor`**: is an abstract class with the logic to build queries and chain constraints, and a contract for driver-specific querybuilders.

**`<DriverSpecific>\QueryProcessor`**: extends and implements Spider's `QueryProcessor`, and basically handles all the query building constraints. I would like this to be more-less plugging in a vendor-specific grammar. The actual compiling of the query would me as much on the abstract class as possible.
## API

We should definitely learn from all the SQL querybuilders out there, and I'd like the learning curve to be a shallow one, but there are several graph-specific concepts that also need to be reflected in the query builder (like traversals) and SQL elements that make no sense (like JOIN).

That said OrientDB's SQL and Neo4j's CYPHER are probably good places to look for inspiration.

``` php
$builder = new QueryBuilder($connection);
$results = $builder
    ->select($fields)
    ->from('label or class')
    ->where()
    ->andWhere() // etc
    ->get();

// And for graph stuff
$results = $builder
    ->traverse()
    ->start($id)
    ->out('owns')
    ->depth(3)
    ->strategy($x)
    ->get();

// It would also make sense to be able to nest the two.
$activeUsers = $builder->new()->select()->from('Users')->where('active', true);

$query = $builder
    ->traverse()
    ->start($activeUsers)
    ->out('friends')
    ->depth(1)
    ->get();
```

Any thoughts? Concerns? Glaring wrongs? Please don't be shy.

It's best to put off schema stuff for now. Also note that Models are coming soon, and will utilize a lot of this.

**Comment by dmill-bz** [comment]
I can see one issue at the moment with the way you handle traversals. This implementation looks a lot like how gremlin (imperative) works. You'll end up with a lot of `->out()->out()->out()` and although this is absolutely functional, you'll loose the beauty of declarative query building.

My personal feeling is that there shouldn't be any separate traversal stuff. Graph links should probably be handled like you would handle joins (kinda) in a relational db.

It might be interesting to obtain the grammar for some of the languages (OrientSQL or Cypher) and use those to define which methods to set. For example with MySQL's select clause:

```
SELECT
    [ALL | DISTINCT | DISTINCTROW ]
      [HIGH_PRIORITY]
      [STRAIGHT_JOIN]
      [SQL_SMALL_RESULT] [SQL_BIG_RESULT] [SQL_BUFFER_RESULT]
      [SQL_CACHE | SQL_NO_CACHE] [SQL_CALC_FOUND_ROWS]
    select_expr [, select_expr ...]
    [FROM table_references
    [WHERE where_condition]
    [GROUP BY {col_name | expr | position}
      [ASC | DESC], ... [WITH ROLLUP]]
    [HAVING where_condition]
    [ORDER BY {col_name | expr | position}
      [ASC | DESC], ...]
    [LIMIT {[offset,] row_count | row_count OFFSET offset}]
    [PROCEDURE procedure_name(argument_list)]
    [INTO OUTFILE 'file_name' export_options
      | INTO DUMPFILE 'file_name'
      | INTO var_name [, var_name]]
    [FOR UPDATE | LOCK IN SHARE MODE]]
```

You can tell that for a `QueryBuilder::select()` instance, you need (amongst other things):
- `::from()`
- `::where()`
- `::groupBy()`
- `::having()`
- etc...

You can then map the params fed to each of these methods to your base query syntax string and obtain the final query.
Each language specific query builder could have it's own set of methods that match the query grammar, and then it would be about mapping Spider query methods to the respective ones in the language query builders.
It's a bit tedious but I think it could work pretty well. The only painful part is how to structure it all to avoid naming conflicts.

**Comment by electricjones** [comment]
If there is no specific method for graph traversal, how would you handle constraining a query by relationship (edge) properties?

``` php
// Gets all of Michael's friends who live in England
$sql = $builder->select()->from()->where('username', 'michael')->out('friends', ['country', 'England'])->get();
```

I like the idea of copying MySql as much as possible to down the learning curve, but there are some features of graph databases that I want to expose to the user. Like edge properties, map reducing, and shortest path.

**Comment by dmill-bz** [comment]
Well I wasn't all that clear. Essentially you have a couple of options. One being piping your traversal (`$builder->out()->out()->out()`) or the other is nesting (`$builder->out($builder->out($builder->out()))`). The former makes sense from a traversal perspective but it's totally imperative and may not play well with all the declarative languages and scoping. The second is essentially like making a Builder for SQL where `out()` is a `join()` and this has the advantage of being easier to map to declarative languages, and also providing a single interface for reading the DB via select() and ditching the `traversal()` will be much easier to handle. And this also makes scoping simpler.

Let's imagine the following case:

``` php
/*
 * Get all users that aren't administrators and named michael, then fetch their friend's friends (who live in the UK excluding themselves if they happen to live in the UK.)
 */
$query = new Builder();
$query->select() //indicates read
      ->from('person')
      ->where('userType', Builder::COMPARATOR_EQUAL, 'user')
      ->where('name', Builder::COMPARATOR_EQUAL, 'michael')
      ->store('a')
      ->out('friends')
      ->where('country', Builder::COMPARATOR_EQUAL, 'England')
      ->out('friends')
      ->where('country', Builder::COMPARATOR_EQUAL, 'England')
      ->where(Builder::COMPARATOR_WITHOUT, 'a')
      ->return();

// Now lets check if the user making the call is an admin and if he is lets expand the search to get
// all users that are also administrators, then fetch their friend's friend's

if($currentUser->is('admin'))
{
      $query->?;
}
```

It's really hard to add a scope to your query like this. There is no real clean and simple answer to this. I've been using a php gremlin query builder for the better part of a year and I deal with this daily.

Pros:
- a little less verbose
- might be a tad more intuitive.. not even sure about this.

Cons:
- doesn't play well with scoping (see last point as well)
- more complex than the other solution when it comes to mapping to actual declarative languages
- order matters, if you don't place your `store()`, `where()`, etc. in the right spot you won't get expected results.
- necessary to place store() in any place you'll want to affect the traversal.

The other option is (and keep in mind this is way more verbose than it needs to be, I'm just trying to demonstrate the internals):

``` php
$query = new Builder();
$query->select() //indicates read
      ->store('a')
      ->from('person')
      ->where('userType', Builder::COMPARATOR_EQUAL, 'user')
      ->andWhere('name', Builder::COMPARATOR_EQUAL, 'michael')
      ->andWhere(
            (new Builder)->link('friend', Builder::DIRECTION_OUT)
                         ->where('country', Builder::COMPARATOR_EQUAL, 'England')
                         ->andWhere(
                               (new Builder)->link('friend', Builder::DIRECTION_OUT)
                                            ->store('b')
                                            ->where('country', Builder::COMPARATOR_EQUAL, 'England')
                                            ->andWhere(Builder::COMPARATOR_WITHOUT, 'a')
                           )
      )
      ->return('b');

// Now lets check if user is admin and apply the same scope.
if($currentUser->is('admin'))
{
      $query->andWhere('userType', Builder::COMPARATOR_EQUAL, 'admin');
}
```

The advantage here is that `Builder` could just have a `toString()` mapping for each scenario (`select` `link` etc.) and generating the query would be a recursive breeze. It's one of the cool points of isolating the query in this fashion. 

Pros:
- ordering of the methods is unimportant 
- scoping is really easy. Even if we had to alter `b` it would be simple and we would have multiple ways of doing it: `->andWhere($b = (new Builder)->etc()); $b->andWhere('new condition')` or `$query->get('b')->andWhere('new condition')`. The second example here doesn't work with the first traversal strategy because ordering of methods is important.
- no particular code complexity in `Builder`
- mapping is simple

Cons:
- more verbose (even though I exaggerated it here). There's no need for the end user to have to explicitly create the new queries. It could be internal to the builder via arrays, dot notations, etc... 
- nesting can get ugly (fact of life)

I just think the nesting option is worth taking a deep look into because it helps avoid many pitfalls.

**Comment by dmill-bz** [comment]
Figured I would give an example of a less verbose way of writing the nested query:

``` php
$query->select() //indicates read
      ->store('a')
      ->from('person')
      ->where('userType', 'user')
      ->where('name', 'michael')
      ->where([
          'out' => 'friends',
          'where' => [
              ['country', 'England'],
              [
                  'out' => 'friends',
                  'store' => 'b',
                  'where' => [['country', 'England']],
                  'notIn' => 'a'
              ]
         ]
      ])
      ->return('b'); // or return 'a.b'
```

That's just one example, it could probably be simplified further

**Comment by chrismichaels84** [comment]
So, this would return
```javascript
[
   [0] => [
        'username' => 'michael' 
        ]

   ]
]
```

**Comment by electricjones** [comment]
**edited for clarity**

I like the declarative nature of this query builder because I feel it would be an easier transition from those in the SQL world. I can also see how it would be possible to limit queries based on edge properties (only those friends who have been friends more than 3 years).

In the above case, what would the query return exactly?
  A. michael (with details) AND michael's friends AND michael's friend's friends (with details)
  B. michael (with details) AND michael's friend's friends (with details)
  C. just michael's friend's friends (with details)

or something else entirely?

**Comment by dmill-bz** [comment]
It would return C. But thinking about it you could very well write it as : 

``` php
$query->select('b') // or a.b
```

With no return. 
I originally added the return to match `Cypher`'s `RETURN` section but it might not be necessary.
In that case `select() // no param` would return `select('a')`, that is to say users named michael that have friends in England who have friends in England.

The cases A and B you mention could be obtained by using a method like `::tree()` on the query.

``` php
// Once the query from my previous post is read you could do:
$query->select('b')->...->one(); // returns the first entry of friend's friends
$query->select('b')->...->all(); // returns all friend's friends
$query->select('b')->...->tree(); // returns a nested set of michaels AND their friends AND their friend's friends
$query->select('a')->...->tree(); // returns a nested set of michaels AND nothing really
$query->select('b')->...->path(); // returns the same set as tree() just formatted differently
```

I'm not sure whether or not path and tree should actually take into account what's in the select. Maybe you would have to explicit what you want returned inside those methods instead of the select. Worth thinking about.

**Comment by electricjones** [comment]
I like using `select()` at the beginning of a query to indicate read and `insert()`, `delete()`, and `update()` to indicate write operations. Makes it easier for the driver. I would keep `return()` and then add the additional methods. So `return()` does nothing by itself.

I like the direction this is heading. Just to make sure I'm clear, here is a query that returns a nested set of
- The first user named "michael"
- michael's friends who have been friends longer than 3 years, only selecting their username and country

``` php
$query->select() // indicates read, select *
      ->from('users')
      ->where('username', 'michael')->first()
      ->store('a')
      ->where([
          'out' => 'friends'
          'where' => ['friends.years', '>', 3],
          'only' => ['username', 'country']
          'store' => 'b'
      ])
      ->return('b') // return() by itself returns last stored
      ->tree();
```

Or, maybe something a tad more fluent. Remove `return()`, use `tree()` and the like more like a constraint, and `get()` fires query.

``` php
$query->select()
    ->from('users')
    ->where('username', 'michael')->first()
    ->store('a')
    ->also([
        'select' => ['username', 'country'],
        'where' => [
            'out' => ['friends', ['years', '>', 3]],
        ],
        'store' => 'b',
    ])
    ->tree()
    ->get(); // fires the query
```

This, to me, is pretty readable.

Either of these would return

``` javascript
{
   'username': 'michael',
   'country': 'USA',
   'nickname': '...' // and whatever other properties users have
   'friends': [
       {
          'username': 'eliza',
          'country': 'Spain'
       },
       {
          'username': 'jon'
          'country': 'England'
       },
       // etc
   ]
}
```

**Comment by dmill-bz** [comment]
At this point a lot of it is going to boil down to personal preference. But I kinda saw two ways of writing that query:

``` php
$query->select() // indicates read, select *
      ->from('users')
      ->where('username', 'michael')
      ->limit(1)
      ->where([
          'outE' => 'friends',
          'where' => [
              ['years', '>', 3],
              ['inV',
               'where' => ['username', 'country'],
               'store' => 'b']
          ]
      ])
      ->return('b') // return() by itself returns last stored
      ->tree();
```

or

``` php
$query->select() // indicates read, select *
      ->from('users')
      ->where('username', 'michael')
      ->limit(1)
      ->where([
          'out' => ['where'=>[['label', 'friends'], ['years', '>', 3]]],
          'where' => [['username', 'country']],
          'store' => 'b'
          ]
      ])
      ->return('b') // return() by itself returns last stored
      ->tree();
```
- No need for `store('a')`
- Make use of `limit()` (doesn't mean we can't have a shorthand `first()`). This will help in using `offset()` as well.
- consider `out` to be a shorthand for `outE`, so it should be structured like a `QueryBuilder` array.
- The traversal part of the `QueryBuilder`, that is to say `out`, `outE`, `outV`, `in`, `inE`, `inV` don't need to be a key/value pair. We only treat it as such if necessary.
- The second way would be transformed into the first by the system.

Of coure the above can be simplified. Though the more we go down simplification road, the better it would probably be to break the `QueryBuilder` into several classes that extend from it. For example we could imagine a `LinkQueryBuilder` that hands input arrays from `out` and co.

**Comment by electricjones** [comment]
All right, I think it's time to crank out some interfaces and tests. I'm gonna work on this today and tomorrow. I'll push some commits this week, I hope. Thanks for your help. I think I will more/less shadow OrientDB's SQL, minus the Traverse command for now. I have never used Cypher, so as I push commits, I wouldn't mind some feedback from someone who knows cypher.

**Comment by dmill-bz** [comment]
Sure,
I'm not that familiar with cypher but I'll try and help on that end.
I'll also see if I have time to make gremlin-server driver as well.

**Comment by electricjones** [comment]
I have pushed an extremely rough draft of a working query builder with orientdb implementation to the `query-builder` branch. It only executes `select` commands with various `where` constraints for now. No traversals, no relationships, and no CUD. But, the structure is there. Next week, I plan to fill out the CUD, clean up what I have here, and (hopefully) have good start. After that, it'll be time to tackle the all-important edges, traversals, and the like.

I have also (mostly) changed the name to a CommandBuilder instead of a QueryBuilder.

The architecture is simple. 
1. The `Commands\Builder` object is a fluent query builder 
2. The `Builder` produces a `Commands\Bag` that holds all the various components of a command. 
3. When the command is executed (via `all()` or whatever, the `Builder` passes the `Bag` to a driver-specific `CommandProcessor` 
4. The `CommandProcessor` returns a valid `Command` object with the native script. 
5. The `Builder`, then passes that valid `Command` script off to the connection and the driver itself to execute the command and return the results.

So, a potential driver author would have to implement a `Driver` contract and a `CommandProcessor` contract, both with only a few methods.

Just wanted to document all this for the time being.

**Comment by dmill-bz** [comment]
I'm currently writing a gremlin-server driver to see how things work and there are a few things that seem odd to me.

First off. The mapping of DB results to objects in the driver just seems out of place. It shouldn't be the driver's place to know what the query is returning. 
In the following case:

``` php
$query = UserRecord::select();
$userRecords = $query->all();
```

It's the Query that gets the `all()`, `one()`, `tree()`, etc. calls. It should be the query's job to populate the records (as it also knows which record spawned it). I think the `SpiderRecord` in the driver is too premature, or at least not properly implemented. 

Maybe the `Driver` should implement multiple formatting methods for different result sets. path, tree, vertices, properties, scalar and the query should call those appropriately.

For instance, `$query->all()` would in reality do:

``` php
$result = $query->execute();
$result = Driver::FormatAll($result);
// Do mapping of results to objects
$return $objectArray;
```

(Doesn't have to be exactly like this but it's for the idea)

Also another issue I noticed is that graph elements have metaProperties and properties. 
Meta properties are things like `id`, `label`, `type`. Properties on the other hand can be anything the user sets (including one of those three). With the current structure where SpiderGraph is populated with a combination of both this can lead to conflicts (if say the vertex has a `type` property for example).

Consider the following to see where conflicts could arise (you can see that properties is set in SpiderRecord to avoid said conflicts):

``` php
    /**
     * Hydrate a SpiderRecord from a gremlin-server response array
     */
    protected function arrayToSpiderRecord($array)
    {
        // Or we map a single record to a Spider Record
        $spiderRecord = new SpiderRecord();
        $properties = [];
        foreach($array['properties'] as $key => $value)
        {
            $properties[$key] = $value[0]['value'];
        }

        $spiderRecord->add([
            'id' => $array['id'],
            'label' => $array['label'],
            'properties' => $properties,
        ]);
        return $spiderRecord;
    }
```

Last but not least. Setting up drivers with a config array means that you won't be able to see options for each driver through docblock generated APIs (unless specified with `@property`).
Instead I think we should set the class properties and extend a base `Object`class that would map an array to those properties

``` php
class Driver extends DriverInterface{
    public $someProp;
}

$object = new Driver(['someProp' => 25]);
```

This will make documenting much nicer and probably play well with IDEs.

---

While I'm at it. I also don't think Drivers should come with their CommandProcessor because some DBs accept multiple languages. Like gremlin-server and probably orientDb and Neo4J (who may accept gremlin). So maybe a separation is required here.

**Comment by dmill-bz** [comment]
Let me know if I should create a more detailed issue for each of these points. So we can go over them separately.

**Comment by electricjones** [comment]
Thanks for your thoughts and for the basic gremlin server driver. I feel like this is all shaping up nicely. I'm able to do a lot of work on this repo the rest of this week as I need to get this into alpha pretty quickly for a related project.

Here are my responses to the above, one-by-one.

**Mapping Results**
Mapping results to `SpiderRecord`s in the Driver has always felt awkward to me. I've tried it in other places like the `Connection` and on its own.

The problem is twofold. First, people should be able to use these component parts independently. Different layers of abstraction will build on top of each other. That is, use the `Driver` without using the `CommandBuilder`. Once Models come around, they should be able to use the `CommandBuilder` without using the `Driver` directly. 

With that in mind, the Driver MUST return something consistent. In the orient driver, I am using a third-party language binding and I expect most drivers to do the same. Those bindings will each return their own flavor of records. If it is the `CommandBuilder` or `Connection` or something else that is responsible for mapping, I don't know how to consistently map an unknown record type to a consistent `SpiderRecord`.

Maybe each driver could/should contain a `RecordTransformer` of some kind? If this one needs more discussion, lets open a new issue and copy some of this.

**Meta Properties**
Completely agree. Maybe records should be mapped in such a way that every result has a `meta` bag with meta properties?

``` php
$result = query->one();
$result->username; // normal property for username
$result->birthday; // normal property birthday
$result->label; // normal property for label, maybe like a tag system or whatever
$result->meta->label; // meta property for class or type, automatically populated
```

While on that topic. We should come up with a standard vocabulary. Different databases have different terms for `label`, `class`, `property`, `field`, etc. May be best just to stick with something like Neo4j or Gremlin since they are the most used.

**Driver Configuration**
Love it. I'll implement that today.

**Command Processor Placement**
True that Orient, Neo and most will accept multiple query languages. And, I'm good splitting the `CommandProcessor` out. My concern is in Driver creation. The goal of the entire project is to make it as easy as possible to build drivers and it just seemed easier to me to have them in the same place. It also cuts down on dependencies, but that's not such a big deal with composer.

**Splitting the repo**
I guess the above comment is based on my intention to split the repo into several repos, and I'm not sure its a great idea. My thought was:

`spider/spider-core`: contracts, CommandBuilder, Models, Connections, etc
`spider/spider-orient`: orient db driver, CommandProcessor, etc
`spider/spider-gremlin-server`: gremlin server driver, CommandProcessor (no idea how to do this), etc
`spider/spider-<driver>`: other drivers
`spider/docs`: documentation up on readthedocs.com
`spider/spider`: has a composer.json that pulls in all first-party drivers and the core
`spider/spider-laravel`: a bridge for the Laravel Framework
And so on.

Is this over complicating things? I guess it doesn't really matter if you pull in other drivers you don't need. My thought was that people may want to use the drivers without the rest, but that probably won't happen often, and the extra files aren't that big a deal.

Also, just to let you know. I DO want to change the php namespace to just `Spider\`. Drop the `Michaels`.

**Comment by electricjones** [comment]
I have pushed `driver-configuration` branch with updates for driver configuration. The interface has changed. I dropped the idea of config being separate from credentials. Now, any driver that extends `AbstractDriver` can be initialized with a `$properties` array (hostname, port, etc) which will be mapped to the internal properties of the driver. It also includes a `setCredentials()` method so the credentials may be set after instantiation. Refactored tests to pass.

ToDo: Handle defaults?

**Comment by dmill-bz** [comment]
That's great!
I'll refactor the PR to take those changes into account. The defaults can just be hardcoded into the classes no? 

As far as splitting the repo and command processors go I think the split is a good idea. It might be a tad more work for people implementing but it'll flow way better once up and running.
Drivers should always just take string queries. If you want to use a language builder (with or without the driver) you can simply add it via composer. I actually expect that to be more frequent than using the driver on it's own.

So with that in mind I think you would want different repos for drivers and for languages. To simplify things for the end users that don't care about the separation maybe the drivers could simply require the language processors.

I'm going to separate some of our discussions into other issues so we can better track/close them

**Comment by dmill-bz** [comment]
As a response to the Command Processor placement:

You could imagine a scenario where users would like to use a REST driver for a DB over the websocket driver for the same DB. They shouldn't have to create a new commandProcessor.. If that makes any sense?

**Comment by electricjones** [comment]
I hadn't considered that. Splitting them is definitely the way to go.

I'm also going to close this issue. I think we've changed from its original topic and specific issues are easier to work with.
