### ISSUE TITLE
Simplify Driver Interface by removing read/write commands

### ISSUE THREAD

**Issue by electricjones** [spider/spider#78]
Now that I have pushed commit 8a21b1a947b875779d876897ca0942825dd8b037, Orient uses sql batch scripts for all operations. That eliminates the need for different read/write commands. We also have `runReadCommand()` which just doesn't make any sense at all, lol.

I propose we simplify the Drivers and Interface to simply `runCommand()` and `executeCommand()`

Any reason not to?

**Comment by dmill-bz** [comment]
None that I can think of. This will automatically fix some satellite issues with passing `Command` to `Query` as well.

**Comment by dmill-bz** [comment]
Closing this since the PR was merged.
