### ISSUE TITLE
PHP Support, Code Style, and Guidelines

### ISSUE THREAD

**Issue by electricjones** [spider/spider#83]
An open discussion about standards for spider.
- Would anyone object to moving the minimum requirements from 5.4 to 5.5 or even 5.6? I would really love to use generators in the orient driver and variadic functions would be super helpful as well. I feel like anyone using a graph database isn't using $3/month hosting and has more control over their php versions.
- I'd like to stick with PSR2 style as much as possible. If we diverge, just make it consistent.
- Scrutinizer is giving a fuss about equal signs not being aligned. Thoughts?

Anything else to consider?

**Comment by smolinari** [comment]
IMHO

PHP Version. Absolutely! 
PRS2 -> ok! Should there be any divergences, they should only be for a necessity and should also be documented somewhere. Probably in a contributors.md?
Can you give an example of code for the equals sign issue?

Scott

**Comment by dmill-bz** [comment]
We can change the scrutinizer behavior for PSR2 only. We'll just have to go through the enabled features to make sure we aren't forgetting anything. 
Here's how I feel about aligning equals signs: 
It's cool with `const` declarations. Otherwise it's a pain. I'm not against removing this check entirely.

PHP version : I'm not against bumping the requirements up to `5.6`.
I think all things considered `5.5` is definitely a doable bump. I don't know how common `5.6` is though.

**Comment by electricjones** [comment]
Scrutinizer complains about

``` php
$one = 1;
$anotherOne = 2;
$aThird = 3;
```

It wants

``` php
$one         = 1
$anotherOne  = 2
$aThrid      = 3
```

**Comment by electricjones** [comment]
I'll do some research on `5.6`. The equals being aligned bothers me, except in constants. It makes it too hard to read and is just a pain.

**Comment by smolinari** [comment]
> It wants
> 
> ```
> $one               = 1
> $anotherOne  = 2
> $aThrid           = 3
> ```

I agree with constants lining up. Normal variables shouldn't have to. (and I saw that Github's editor adds spaces. Strange). Do variables need to be initialized with values at the top of the classes?

5.6 isn't used much compared to 5.4 or even 5.5. I'd bet with 7 coming, there will probably be more of a jump to 7 than to 5.6 too. 5.5 will be EOL'ed in 10 months and active support dropped a month ago. With all that in mind, I would still say 5.6 should be the minimum. 

Spider is going to be so cool, people will do anything to get it anyway, right? :smile: 

Scott

**Comment by electricjones** [comment]
According to PSR (and good sense for APIs), yes. But PHP doesn't require it. We do initialize all of our class properties though.

**Comment by electricjones** [comment]
I agree. I think 5.6 is a good requirement. If we get complaints, we may be able to down that, but I doubt it will be a problem.

I'd love to use PHP7, but it's just too soon for that. I am super excited about return types.

**Comment by dmill-bz** [comment]
Yeah same. The whole typecasting changes are really exciting. I, however, feel like it's missing the possibility to have multiple signatures along the lines of what java does: 

``` php
class A {
   public function method(String $a, String $b): String {
      return $a . ' ' . $b;
   }

   public function method(String $a): String {
      return $this->method('Hello', $a);
   }

   public function method(): String {
      return $this->method('world');
   }
}

$a = new A();
$a->method(); // Hello world
$a->method('dylan'); // Hello Dylan
$a->method('Some', 'text'); // Some text
```

That would make it complete. Because right now the more we typecast (which is good) the less flexibility we have (which is bad).. We're experiencing this right now with out `internal` prefixes.

Anyways I digress, lets go with `5.6`. It will simplify travis testing as well.

**Comment by electricjones** [comment]
Cool. So, to recap and close this:
- Tell scrutinizer to use PSR
- Ignore the aligned equal signs for variables, keep them for constants.
- Bump to 5.6
- Beg PHP to allow multiple signature is 7.1 :smirk_cat: 

The other thing I'm excited about in PHP7 is anonymous classes. It'll make testing SO much simpler.

**Comment by dmill-bz** [comment]
Yeah definitely!

**Comment by electricjones** [comment]
Great. Do you know how to configure scrutinizer?

**Comment by dmill-bz** [comment]
Yes, I'll have a look around if you want.

**Comment by electricjones** [comment]
I would appreciate it. You can commit directly to `develop` rather than a pr for something so simple.

**Comment by dmill-bz** [comment]
I'll document the scrutinizer documentation so we can check we all agree in the PR #84 . I think it's safe if I bump it up to 5.6 as well.

**Comment by dmill-bz** [comment]
Merged the PR. Closing this as I think we should be good.
