### ISSUE TITLE
Validation and Command Bags

### ISSUE THREAD

**Issue by electricjones** [spider/spider#88]
There should be a way to validate a Command Bag. To me, this belongs on the `Bag` itself. So, this issue opens up three questions around that functionality:
1. What constitutes a valid `Bag` 
2. What messages are sent to the user for invalid bags?
3. Would it be best to use or implement a general validation framework?

Speaking on **number three**, there are many other places throughout spider that will need validation. I feel it would be best to find a good composer package that is capable of validating objects and primatives against a schema and producing meaningful messages about invalidity.

A quick packagist search showed these promising candidates:
- https://packagist.org/packages/illuminate/validation - may be overkill, has a lot of dependencies
- https://packagist.org/packages/respect/validation - without looking too deep, my favorite
- https://packagist.org/packages/symfony/validator - super standard, my other favorite

Some other contenders:
- https://packagist.org/packages/cakephp/validation
- https://packagist.org/packages/siriusphp/validation

Open to any other suggestions, though. Thoughts?

**Comment by electricjones** [comment]
I'm working on this today if anyone has any thoughts.

**Comment by smolinari** [comment]
Flying over the validators, I would say "respect" looks the most promising for the job of command bag validation. A bit of overkill too. But, theoretically, if someone is using Spider for their backend, they'd have a powerful validation tool built in to go with it. Someone like me! :smile:

Scott

**Comment by electricjones** [comment]
Well, I really liked "respect" but it did turn out to add more complexity than was really needed. Since Spider shouldn't be doing any user-generated input validation, nearly all those rules were overkill. I just whipped up a super-simple generic Validator. It should be easy to make this validator accept Respect rules and Symfony rules, though. In any case, I lived and learned. You can see the Validator and its proposed use in validating CommandBags in PR #86.

**Comment by smolinari** [comment]
I was going to ask if they aren't all a bit of overkill, but decided not to. I wasn't sure what you were looking for in terms of validation, to be honest. Glad you figured it out. Looks good! :+1: 

Scott
