### ISSUE TITLE
OrientDB is at 2.1.4

### ISSUE THREAD

**Issue by smolinari** [spider/spider#94]
Should the tests be made against that version? Or it doesn't matter?

Scott

**Comment by dmill-bz** [comment]
Do you want to try and give this one a go Scott? I'm also currently upgrading gremlin-server and gremlin driver to the latest.

**Comment by smolinari** [comment]
Hehe....ok. ODB is actually at 2.1.5 now and 2.1.6 is around the corner along with 2.2.0. Supposedly 2.2.0 is going to have some performance improvements in it too. I just wish they'd come up with a bit more stability. 

Scott

**Comment by dmill-bz** [comment]
Yeah and I've been following the progress of orient 3.0 and that's going well too.

**Comment by electricjones** [comment]
Agreed. I'm away for the week, but Spider is just about the only thing on my list through the end of the year. I'll add this to my todos :)

**Comment by smolinari** [comment]
Hmm...I am plucking away at this. Working with the develop branch and ODB 2.1.5, I ran into this. 

```
S...........................................................PHP Fatal error:  Class 'brightzone\rexpro\Connection' not found in /opt/appserver/webapps/spider/tests/Fixtures/GremlinFixture.php on line 29

Fatal error: Class 'brightzone\rexpro\Connection' not found in /opt/appserver/webapps/spider/tests/Fixtures/GremlinFixture.php on line 29

```

So, I figured out the problem and I refactored the namespace to `Brightzone\GremlinDriver`, which fixed the above, but now I am running into this. 

```
S............................................................S.  63 / 112 ( 56%)
..EE........S...............SS...................

Time: 19.9 seconds, Memory: 25.00Mb

There were 2 errors:

1) Spider\Test\Unit\Drivers\Gremlin\DriverTest::testWriteCommands
Brightzone\GremlinDriver\ServerException: The server processed the request but there is no result to return (e.g. an {@link Iterator} with no elements). :  >

/opt/appserver/webapps/spider/vendor/brightzone/gremlin-php/src/Connection.php:792
/opt/appserver/webapps/spider/vendor/brightzone/gremlin-php/src/Connection.php:333
/opt/appserver/webapps/spider/vendor/brightzone/gremlin-php/src/Connection.php:468
/opt/appserver/webapps/spider/vendor/brightzone/gremlin-php/src/Workload.php:78
/opt/appserver/webapps/spider/vendor/brightzone/gremlin-php/src/Connection.php:471
/opt/appserver/webapps/spider/src/Drivers/Gremlin/Driver.php:105
/opt/appserver/webapps/spider/src/Drivers/Gremlin/Driver.php:129
/opt/appserver/webapps/spider/tests/Unit/Drivers/BaseTestSuite.php:223

2) Spider\Test\Unit\Drivers\Gremlin\DriverTest::testTransactions | it rollbacks properly on transactional graph
Brightzone\GremlinDriver\InternalException: gremlin-php driver has thrown the following error : A graph object needs to be specified

/opt/appserver/webapps/spider/vendor/brightzone/gremlin-php/src/Connection.php:788
/opt/appserver/webapps/spider/vendor/brightzone/gremlin-php/src/Connection.php:542
/opt/appserver/webapps/spider/src/Drivers/Gremlin/Driver.php:233
/opt/appserver/webapps/spider/tests/Unit/Drivers/BaseTestSuite.php:250
/opt/appserver/webapps/spider/vendor/codeception/specify/src/Codeception/Specify.php:117
/opt/appserver/webapps/spider/vendor/codeception/specify/src/Codeception/Specify.php:54
/opt/appserver/webapps/spider/tests/Unit/Drivers/BaseTestSuite.php:269
```

Not sure what the issue is other than possibly my software on the gremlin side is outdated. I am going to play with the vagrant box now. 

Scott

**Comment by dmill-bz** [comment]
Hmm I merged a PR for this the other day :  246b03f089920b38f3be6957787cb88903d9bc74
Did you pull the latest version and `composer install`?

Oh also you will need to use `gremlin-server 3.0.2`. I'm going to doublecheck the vagrant configuration right now to make sure it's in sync with the CI build

**Comment by smolinari** [comment]
It isn't. I am playing around with the vagrant box right now and it has ODB 2.1.0 and Gremlin 3.0.0. Neo4J is also an older version too. What version Neo4J should it be installing?

I am not sure what I did merging Spider's upstream repo. 

Develop is the branch I should be pulling from, isn't it? 

Scott

**Comment by dmill-bz** [comment]
Yes. I also just put the up the following PR: #100 which should address the gremlin-server version for vagrant. 

The PR also reintroduces the composer.lock file which should ensure that you get the same dependencies as travis and myself when you composer install.

**Comment by smolinari** [comment]
I just fired up the vagrant box and it is working. I haven't ran any tests yet. I'll get to that this evening.

There seems to be an issue with the way ODB is initially started. It isn't doing its proper initialization work. Not sure why, but I can tell, because ODB isn't updating the `orientdb-server-config.xml` file with the needed user elements. This, in turn, means Studio keeps annoyingly asking for htaccess credentials, when they aren't needed. Could it be a user permissions conflict, because the orientdb.sh doesn't have a user or dbroot path added? 

It would also be nice in general, if the servers would be started as services, when working with them. (to start and stop them, when doing other work on the servers). I can get this done with ODB, but I am not sure about Gremlin or NEO4J. Should I attempt the ODB changes? Is this even important?

Scott

**Comment by smolinari** [comment]
And now ODB is at 2.1.6

https://github.com/orientechnologies/orientdb/releases/tag/2.1.6

Scott

**Comment by electricjones** [comment]
Okay, this is great. I'm not sure how to support this in automated testing, because I don't know that I only want to test against the most cutting edge implementations of all these databases. Teams are sometimes slow to upgrade. Any thoughts? I don't know how to make Travis test against multiple database versions (say the latest 3?)

**Comment by smolinari** [comment]
From what I've been reading between the MongoDB and OrientDB communities, it seems quite often that users of databases hang behind quite a bit from upgrading. However, that being said, theoretically, patch versions should be backwards compatible too. So, even if Spider supports the current patch version, it should also work for older versions too. 

Scott

**Comment by dmill-bz** [comment]
For testing against different server versions it's pretty easy, you just have to add an `env` to the travis configuration. We can do:

``` yml
env:
  - NEO4J_VERSION="2.2.5" GREMLINSERVER_VERSION="3.0.2" ORIENT_VERSION="2.1.6"
  - NEO4J_VERSION="2.2.4" GREMLINSERVER_VERSION="3.0.1" ORIENT_VERSION="2.1.0"
  #etc...
```

Of course this multiplies the builds very quickly. (both those envs are run against all supported PHP versions)

**Comment by smolinari** [comment]
In general, I would vote for testing with the most current patch version or maybe only updating to the even numbered patch versions, to reduce having to update testing schemes too often. There shouldn't be issues with BC breaks between the patch versions.

When a major point release or major release is out, I'd vote for supporting two versions, possible with a sunset scheme based on point releases. 

Actually, since there are so many possible combinations with the servers supported, I am wondering if the database APIs should plug-in-able. So, each plug-in would be versioned and tested with their respective database? Hmm....

Thinking out loud here. LOL! 

Scott

**Comment by dmill-bz** [comment]
Yeah we originally thought of that but there were some drawbacks to operating like that as well. 

I think the two latest minor versions (latest patch) should be supported. It might be cool to have a comprehensive error for features covered that don't exist in older versions but I'm not quite sure how you would accomplish that in php

**Comment by smolinari** [comment]
Yeah, supporting a number of databases, with different languages, adds a good bit of complexity. 

Scott

**Comment by electricjones** [comment]
> I think the two latest minor versions (latest patch) should be supported. It might be cool to have a comprehensive error for features covered that don't exist in older versions but I'm not quite sure how you would accomplish that in php

I agree with the last two minor versions. In all reality, it would likely work for other versions and the community can help fill gaps if they need older versions. I will do some look into errors covered for features that don't exist. I think we are on the way with the `UnsupportedException` we already have. It would just be the driver's responsibility to alert the rest of the system that a feature is not supported in the current version.

**Comment by smolinari** [comment]
I've been playing around and have some small changes made, to get the ODB 2.1.6 server running properly. 

For now, when running the tests, I get these errors, which have nothing to do with ODB. 

```

S............................................................S.  63 / 112 ( 56%)
..EE........S...............SS...................               112 / 112 (100%)

Time: 46.4 seconds, Memory: 28.50Mb

There were 2 errors:

1) Spider\Test\Unit\Drivers\Gremlin\DriverTest::testWriteCommands
Brightzone\GremlinDriver\ServerException: The server processed the request but there is no result to return (e.g. an {@link Iterator} with no elements). :  >

/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Connection.php:800
/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Connection.php:341
/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Connection.php:476
/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Workload.php:78
/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Connection.php:479
/var/www/public/Spider/src/Drivers/Gremlin/Driver.php:105
/var/www/public/Spider/src/Drivers/Gremlin/Driver.php:129
/var/www/public/Spider/tests/Unit/Drivers/BaseTestSuite.php:223

2) Spider\Test\Unit\Drivers\Gremlin\DriverTest::testTransactions | it rollbacks properly on transactional graph | examples index 0
Brightzone\GremlinDriver\InternalException: gremlin-php driver has thrown the following error : A graph object needs to be specified

/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Connection.php:796
/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Connection.php:550
/var/www/public/Spider/src/Drivers/Gremlin/Driver.php:233
/var/www/public/Spider/tests/Unit/Drivers/BaseTestSuite.php:250
/var/www/public/Spider/vendor/codeception/specify/src/Codeception/Specify.php:118
/var/www/public/Spider/vendor/codeception/specify/src/Codeception/Specify.php:55
/var/www/public/Spider/tests/Unit/Drivers/BaseTestSuite.php:269
```

And ideas @PommeVerte?

Scott

**Comment by electricjones** [comment]
Both of those tests are from corrupted Gremlin Databases. We had the problem before. They are local problems because you and I needed to rebuild or wipe clean the gremlin data-store. So, the errors shouldn't pop up anywhere else :)

PS: I am back pretty full time to Spider on Monday, I hope. Thank you both for your work this week :)

**Comment by smolinari** [comment]
I haven't done much. More playing and learning than anything else. 

How can I fix the issue so my local tests will work?

Scott

**Comment by dmill-bz** [comment]
what version of the server are you running?

**Comment by smolinari** [comment]
```
export NEO4J_VERSION="2.2.4"
export GREMLINSERVER_VERSION="3.0.2"
export ORIENT_VERSION="2.1.6"
```

Scott

**Comment by dmill-bz** [comment]
ok I had a closer look at your errors. It looks like there are two separate issues. The first one is that your graph isn't populated. The second is that the transactional (neo4j) graph isn't instantiated. 

In essence it sounds like your configuration isn't right. Have you followed all the steps here : https://github.com/spider/spider/blob/master/docs/contributing.md

The individual files (and download link) will need updating but you can find the configuration files here : https://github.com/PommeVerte/gremlin-php/tree/master/build/server (or in the `vendor/brightzone/gremlin-php/build/server/` folder)

**Comment by smolinari** [comment]
I'll give it a try to see what is missing or wrong for Gremlin. However, I thought the vagrant box was supposed to be set up to run everything necessary for testing automatically. I had pulled in your branch into my local repo, to get the update to Gremlin 3.0.2. Maybe I made a mistake with that?

Scott

**Comment by smolinari** [comment]
Ok. 
1. the REST API doesn't bind to all network interfaces, so I had to change the neo4j properties to allow my browser access. Then I could change the password to "j4oen". Why not use the standard password for testing? It would save the step. 

That being done, now I am getting these errors. 

```
S...........................................................EEE  63 / 112 ( 56%)
EEEEEEEEEEE.S...............SS...................               112 / 112 (100%)

Time: 44 seconds, Memory: 27.75Mb

There were 14 errors:

1) Spider\Test\Unit\Drivers\Gremlin\DriverTest::testFormatPath
Brightzone\GremlinDriver\ServerException: The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : No such property: g for class: Script1 >

/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Connection.php:800
/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Connection.php:341
/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Connection.php:476
/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Workload.php:78
/var/www/public/Spider/vendor/brightzone/gremlin-php/src/Connection.php:479
/var/www/public/Spider/tests/Fixtures/GremlinFixture.php:33
/var/www/public/Spider/tests/Unit/Drivers/Gremlin/DriverTest.php:22
```

All 14 errors are the same.

I am stuck again.

Scott

**Comment by dmill-bz** [comment]
> Why not use the standard password for testing

Last I tried Neo4j complained that the password needed to be changed before operations could be performed. Hence the changing of the password.

> I had pulled in your branch into my local repo, to get the update to Gremlin 3.0.2. Maybe I made a mistake with that?

Chances are my branch wasn't suffisent to get `gremlin-server 3.0.2` working. That's why I needed you guys to confirm.

> All 14 errors are the same.

This error indicates that when the server was turned on it didn't populate the variable g with the traversal object. It's hard to debug this without the server output (that should give a warning)

**Comment by dmill-bz** [comment]
Can you manually turn the server off and back on again? you might need to kill it after looking it up with `sudo lsof -i`

**Comment by smolinari** [comment]
> Last I tried Neo4j complained that the password needed to be changed before operations could be performed. Hence the changing of the password.

Hmm... yes. Before you can continue with the server, it asks for a new password. Maybe we could  automate this step by replacing the neo4j `/data/dbms/auth` file with a preconfigured one?

Checking to see if we can go to Gitter......

Scott

**Comment by smolinari** [comment]
@chrismichaels84 - Hey Chris. I was having issues with ODB working properly and I fixed it by adding chown to the bootstrap.sh to make the ODB files root owned. For some reason they were installing as user "501". I still also had issues with permissions and found out if I started ODB with orientdb.sh instead of server.sh, it also works properly. 

Do you know what might actually be the core issue? I made some changes, which are in this PR. See what you think.

https://github.com/spider/spider/pull/103

Scott

**Comment by electricjones** [comment]
I've merged the PR, but I think this must be an OrientDB Core issue. It shouldn't have any bearing on the provisioning and I can't see why this would be desired behavior.

I'm closing this issue for now. I think it needs to be split up a bit.
