### ISSUE TITLE
Checking in

### ISSUE THREAD

**Issue by electricjones** [spider/spider#95]
Well, I've had some deadlines and personal emergencies the last month, but I've finally scraped through most of it. I have the next couple days to get back to Spider and hope to make some progress.

That said, I was originally creating this repo for my team, but the decision was made to go with python over php for our app's backend. We hadn't gotten very far and the more we looked at it, the more media manipulation we wanted the ability to do.

So, Spider is no longer part of that equation. I would like to keep working on it as I think it fills a very important niche and I have learned a lot from the progress. I was wondering what y'all were considering for the rest of the year.

**Comment by smolinari** [comment]
Welcome back! :smile: 

I need something like Spider for my project badly. There is another similar project we could use by Odino, the designer of the Orientdb PHP driver [Orientdb-ODM](https://github.com/doctrine/orientdb-odm), but I am not too thrilled about the fact it uses the HTTP protocol. Odino said it would be relatively easy to implement the binary protocol, but, since I spoke to him, nothing has moved on that project. So, any work on Spider is very much appreciated on my part. 

And anything I can do to help, please let me know. Though, every now and then, when I read how you and Dylan go back and forth on certain topics, I get quite a feeling of inferiority. LOL! My ability to help is limited by my lack of programming experience. But, I am keen to help, if you are keen to overlooking my work a bit more than you would someone with more experience. :smile: 

Scott

**Comment by dmill-bz** [comment]
Hey guys,

Here's my update. I'm still in Paris until the end-ish of November. Until then it's going to be difficult for me to participate all that much. After that though I should have enough time to get this moving along.
Ideally it would be cool to have functioning nested queries and traversal builders for all three current platforms (neo, gremlin, orient) by the end of the year. 
After that I would expect that the ORM layer would come pretty quickly as all the pieces would already be in place. 

@chrismichaels84 you guys went with python for media related reasons, I'm really curious about this as I have media related projects of my own. Do you think you could elaborate a bit on that decision?

**Comment by smolinari** [comment]
I am curious too. I would have thought PHP has an extension for practically any need. 

Scott

**Comment by electricjones** [comment]
I'd be happy to :smile: 

So, we are working on two different, but related, projects. The first is a collaboration studio with artists in mind that allows them all of the project management apps you'd expect (calendar, docs, contacts, etc), but also some that are specifically intended to help artists and geeks work together. We are bringing a lot of the version control methodology from geekdom and the simplicity and beauty from artdom into a single studio.

The second project is an asset management pipeline that fits into that collaborations studio. So, among a lot of other requirements we hashed through in our design stage, we wanted to leave the door open for:
- REST apis
- Simple, but perfomant image filtering, cropping, etc
- Simple, but useful video watermarking and editing.
- The ability to render out and analyze simple 3d models
- The ability to chunk larger binary files
- Simple sound editing and processing
- And most important, utilities for ebook, epub. and mobi creation.

On top of all that, we would like to do some data analysis in the future.

All of this can be accomplished through php (or ruby or java or whatever), and we liked php for its framework community, but we had a hard time finding _quality_ and _maintained_ packages for the sound and video processing, nothing for 3d, and the image processing (likewise) left a little to be desired, though there were plenty of options.

We did, however find sound and video utilities in python. Performance lacks a bit, but another member of my team is hopefully going to pull some of that python code into an extension so we can use C and speed up performance a bit.

The real kicker for us was [Blender](http://blender.org) which is a free and open source 3D creation program that really has the same capabilities as Maya or 3DS Max. The beautiful thing for us is that it also uses Python as a scripting language for extensions and filters. With a little exploring, we realized that we can actually run a Blender processes on a machine and use C bindings to access blender functionality. So, at the end of the day, we can write a python extension for blender that uses blender's C-based, quality image, video, sound, and model rendering and access that functionality form another script (say the webserver). When we came across that, it just seemed smart to keep it all in the same language: python.

We're still working out the details, but it seems promising.

I, personally, am still a PHP fan and would like to keep pushing php forward, especially with php 7. I think it has a good niche to fill. We may use PHP/Laravel for some of the marketing site and other things like that, but its too soon to tell.

We have settled on, and begun development in earnest, with Python/Flask/Blender and a handful of other libraries, some of which we are contributing to.

Our database stack relies on OrientDB for a good chunck of it, heavily cached.

It wasn't entirely my decision, but I'm looking forward to learning more python anyway.

**Comment by electricjones** [comment]
I agree that our goal for the end of the year is a solid, working, driver layer. After that, the abstractions should be relatively simple. It is possible that I will explore porting spider over to python, just for fun, once that is stable. Idk.

For now, Bulbflow and the OrientDriver fills our needs. And we have abstracted the data-manipulation behind a repository, so it shouldn't be difficult to swap out if we want to later.

To @smolinari, I want you to know that I'm self-taught, too. A lot of what I do is just digging around source code, trying stuff, and reading blogs. My degrees are actually in anthropology and education, lol, and truth-be-told, that is what I mostly bring to my current team. I only dev half of the time. We are a small group and a non-profit, so most of our people are part-time or volunteers. I do research toward our end goal -- improving educational curriculum by giving teachers computerized tools that help them create individualized, personalized, multimedia curriculum.

**Comment by dmill-bz** [comment]
That's very interesting! I've been working in the digital/media asset management space for a while now and to be honest there isn't anything much in PHP but there's plenty to work with through the shell and various bindings so we stuck with php. Also, given the architecture we're aiming for (a separate cluster to handle heavy processing) separating DB/core from the heavy duty stuff made sense and also allows us to plug and play way easier.
Let us know how that project moves along I'm really curious to follow the progress.

**Comment by smolinari** [comment]
> The first is a collaboration studio with artists in mind that allows them all of the project management apps you'd expect (calendar, docs, contacts, etc), 

This sounds almost like my project. It's just that we aren't targeting artists in particular. We are targeting anyone, who wants to build web applications. Though, so complicated a web application suite like your team is shooting for is a lot more "detailed" than I would have ever imagined a web app would need to be. Sounds very interesting. 

I wish I had a real team too. My project is me and a couple of guys who are waiting for me to return a result. Then they can join in to help. I am the only "dev" and not a particularly good one, Yet, my project is just a hobby currently. My project is a dream I've had for several years.

At any rate, I would be happy, if Spider became a reality as a first of many small steps and any support for that goal from you gents is totally and greatly appreciated.

Scott

**Comment by smolinari** [comment]
Hey @chrismichaels84 and @PommeVerte 

Hope all is well with you all. 

Is there anything I could possibly get working on myself? 

Scott

**Comment by electricjones** [comment]
I'm closing this for now.
