### ISSUE TITLE
composer.lock is ignored

### ISSUE THREAD

**Issue by dmill-bz** [spider/spider#97]
Hey,

Is there a reason for this? I realize it helps a bit with conflicting lock files when we're in development phase but it would be nice to ensure that `composer install` installs fully tested dependencies.

For conflicts, most of them can be avoided by updating specific packages via `composer update vendor/package` and using `composer update --lock` which will regenerate the hash (which is almost always the point of conflict)

Can I go ahead an remove `composer.lock` from `.gitignore` ?

**Comment by electricjones** [comment]
Yes, composer.lock should be committed. I'm not sure why its ignored.

**Comment by dmill-bz** [comment]
This is covered by PR #100

**Comment by electricjones** [comment]
Closed
